In [1]:
from __future__ import print_function, division
import torch
import torch.nn as nn
import torch.nn.functional as F		
import torch.optim as optim
from torch.optim import lr_scheduler
from torch.autograd import Variable
import numpy as np
import torchvision
from torchvision import datasets, models, transforms
import time
import os


use_gpu = torch.cuda.is_available()

In [2]:
model_conv = torchvision.models.resnet34(pretrained=True)
#print(model_conv)
num_ftrs = model_conv.fc.in_features
model_conv.fc = nn.Linear(num_ftrs, 3)

print(model_conv)
#print('-'*50)
#params = list(model_conv.parameters())
#print(params)
if use_gpu:
	model_conv = (model_conv).cuda()
model_conv.load_state_dict(torch.load('/users/sairam.tabibu/results/kidney/subtype/resnet-34-subtype_classification/resnet1_wei1.pth'))
#print(model_conv.fc.in_features)



ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace)
      (conv2): Co

In [3]:
data_dir = '/shared/supernova/home/sairam.tabibu/kidney'
resize = [224,224]
phase = 'test'

data_transforms = {
        phase: transforms.Compose([
            transforms.Resize(max(resize)),
            transforms.ToTensor(),
            transforms.Normalize([0.596, 0.436, 0.586], [0.2066, 0.240, 0.186])			        
        ]),
    }


image_datasets = {x: datasets.ImageFolder(os.path.join(data_dir, x),
										  data_transforms[x])
				  for x in [phase]}
dataloaders = {x: torch.utils.data.DataLoader(image_datasets[x], batch_size=1,
											 shuffle=False)
			  for x in [phase]}
dataset_sizes = {x: len(image_datasets[x]) for x in [phase]}
class_names = image_datasets[phase].classes

In [4]:
layer = model_conv._modules.get('avgpool')

model_conv.train(False)

def get_vector(t_img):

    my_embedding = torch.zeros((1,512,1,1))
# 4. Define a function that will copy the output of a layer
    def copy_data(m, i, o):
        my_embedding.copy_(o.data)
# 5. Attach that function to our selected layer
    h = layer.register_forward_hook(copy_data)
# 6. Run the model on our transformed image
    model_conv(t_img)
# 7. Detach our copy function from the layer
    h.remove()
# 8. Return the feature vector
    return my_embedding




iter_num = 0
print(phase)
for data in dataloaders[phase]:
    inputs, labels, idx = data
    iter_num += 1
    inputs = Variable(inputs.cuda())
    labels = Variable(labels.cuda())
    if(iter_num%100 == 0):
        print(iter_num)
        print(labels)
    
    
    pic_one_vector = get_vector(inputs)
#     print(my_embedding.shape)
#     print(my_embedding)
    np.save('/users/sairam.tabibu/outputs-34_'+ phase + '/' + str(iter_num), pic_one_vector.numpy().reshape(512,1))
    

    
print("end")
    
    


test
100
tensor([0], device='cuda:0')
200
tensor([0], device='cuda:0')
300
tensor([0], device='cuda:0')
400
tensor([0], device='cuda:0')
500
tensor([0], device='cuda:0')
600
tensor([0], device='cuda:0')
700
tensor([0], device='cuda:0')
800
tensor([0], device='cuda:0')
900
tensor([0], device='cuda:0')
1000
tensor([0], device='cuda:0')
1100
tensor([0], device='cuda:0')
1200
tensor([0], device='cuda:0')
1300
tensor([0], device='cuda:0')
1400
tensor([0], device='cuda:0')
1500
tensor([0], device='cuda:0')
1600
tensor([0], device='cuda:0')
1700
tensor([0], device='cuda:0')
1800
tensor([0], device='cuda:0')
1900
tensor([0], device='cuda:0')
2000
tensor([0], device='cuda:0')
2100
tensor([0], device='cuda:0')
2200
tensor([0], device='cuda:0')
2300
tensor([0], device='cuda:0')
2400
tensor([0], device='cuda:0')
2500
tensor([0], device='cuda:0')
2600
tensor([0], device='cuda:0')
2700
tensor([0], device='cuda:0')
2800
tensor([0], device='cuda:0')
2900
tensor([0], device='cuda:0')
3000
tensor([0], d

23900
tensor([0], device='cuda:0')
24000
tensor([0], device='cuda:0')
24100
tensor([0], device='cuda:0')
24200
tensor([0], device='cuda:0')
24300
tensor([0], device='cuda:0')
24400
tensor([0], device='cuda:0')
24500
tensor([0], device='cuda:0')
24600
tensor([0], device='cuda:0')
24700
tensor([0], device='cuda:0')
24800
tensor([0], device='cuda:0')
24900
tensor([0], device='cuda:0')
25000
tensor([0], device='cuda:0')
25100
tensor([0], device='cuda:0')
25200
tensor([0], device='cuda:0')
25300
tensor([0], device='cuda:0')
25400
tensor([0], device='cuda:0')
25500
tensor([0], device='cuda:0')
25600
tensor([0], device='cuda:0')
25700
tensor([0], device='cuda:0')
25800
tensor([0], device='cuda:0')
25900
tensor([0], device='cuda:0')
26000
tensor([0], device='cuda:0')
26100
tensor([0], device='cuda:0')
26200
tensor([0], device='cuda:0')
26300
tensor([0], device='cuda:0')
26400
tensor([0], device='cuda:0')
26500
tensor([0], device='cuda:0')
26600
tensor([0], device='cuda:0')
26700
tensor([0], de

47400
tensor([1], device='cuda:0')
47500
tensor([1], device='cuda:0')
47600
tensor([1], device='cuda:0')
47700
tensor([1], device='cuda:0')
47800
tensor([1], device='cuda:0')
47900
tensor([1], device='cuda:0')
48000
tensor([1], device='cuda:0')
48100
tensor([1], device='cuda:0')
48200
tensor([1], device='cuda:0')
48300
tensor([1], device='cuda:0')
48400
tensor([1], device='cuda:0')
48500
tensor([1], device='cuda:0')
48600
tensor([1], device='cuda:0')
48700
tensor([1], device='cuda:0')
48800
tensor([1], device='cuda:0')
48900
tensor([1], device='cuda:0')
49000
tensor([1], device='cuda:0')
49100
tensor([1], device='cuda:0')
49200
tensor([1], device='cuda:0')
49300
tensor([1], device='cuda:0')
49400
tensor([1], device='cuda:0')
49500
tensor([1], device='cuda:0')
49600
tensor([1], device='cuda:0')
49700
tensor([1], device='cuda:0')
49800
tensor([1], device='cuda:0')
49900
tensor([1], device='cuda:0')
50000
tensor([1], device='cuda:0')
50100
tensor([1], device='cuda:0')
50200
tensor([1], de

70900
tensor([2], device='cuda:0')
71000
tensor([2], device='cuda:0')
71100
tensor([2], device='cuda:0')
71200
tensor([2], device='cuda:0')
71300
tensor([2], device='cuda:0')
71400
tensor([2], device='cuda:0')
71500
tensor([2], device='cuda:0')
71600
tensor([2], device='cuda:0')
71700
tensor([2], device='cuda:0')
71800
tensor([2], device='cuda:0')
71900
tensor([2], device='cuda:0')
72000
tensor([2], device='cuda:0')
72100
tensor([2], device='cuda:0')
72200
tensor([2], device='cuda:0')
72300
tensor([2], device='cuda:0')
72400
tensor([2], device='cuda:0')
72500
tensor([2], device='cuda:0')
72600
tensor([2], device='cuda:0')
72700
tensor([2], device='cuda:0')
72800
tensor([2], device='cuda:0')
72900
tensor([2], device='cuda:0')
73000
tensor([2], device='cuda:0')
73100
tensor([2], device='cuda:0')
73200
tensor([2], device='cuda:0')
73300
tensor([2], device='cuda:0')
73400
tensor([2], device='cuda:0')
73500
tensor([2], device='cuda:0')
73600
tensor([2], device='cuda:0')
73700
tensor([2], de

94400
tensor([2], device='cuda:0')
94500
tensor([2], device='cuda:0')
94600
tensor([2], device='cuda:0')
94700
tensor([2], device='cuda:0')
94800
tensor([2], device='cuda:0')
94900
tensor([2], device='cuda:0')
95000
tensor([2], device='cuda:0')
95100
tensor([2], device='cuda:0')
95200
tensor([2], device='cuda:0')
95300
tensor([2], device='cuda:0')
95400
tensor([2], device='cuda:0')
95500
tensor([2], device='cuda:0')
95600
tensor([2], device='cuda:0')
95700
tensor([2], device='cuda:0')
95800
tensor([2], device='cuda:0')
95900
tensor([2], device='cuda:0')
96000
tensor([2], device='cuda:0')
96100
tensor([2], device='cuda:0')
96200
tensor([2], device='cuda:0')
96300
tensor([2], device='cuda:0')
96400
tensor([2], device='cuda:0')
96500
tensor([2], device='cuda:0')
96600
tensor([2], device='cuda:0')
96700
tensor([2], device='cuda:0')
96800
tensor([2], device='cuda:0')
96900
tensor([2], device='cuda:0')
97000
tensor([2], device='cuda:0')
97100
tensor([2], device='cuda:0')
97200
tensor([2], de

In [5]:
import numpy as np
a=np.load('/users/sairam.tabibu/outputs_test/115.npy')
print(a)

IOError: [Errno 2] No such file or directory: '/users/sairam.tabibu/outputs_test/115.npy'

In [127]:
a==accumulate

array([ True,  True,  True, ...,  True,  True,  True])

In [7]:
213302+74626

287928

In [21]:
from sklearn import svm
import numpy as np
import os
import matplotlib.pyplot as plt


In [22]:
path = "/users/sairam.tabibu/outputs_train"

# testing - 42907, 13577, 45218
# training - 213302, 74626 , 202912
class1=np.empty((512,213302))
class2=np.empty((512,74626))
class3=np.empty((512,202912))

for i in range(213302+74626+202912):
    a=i+1
    if(os.path.isfile(path + '/' + str(a) + ".npy")):
        mat = np.load(path + '/' + str(a) + ".npy")
        
    if(a%100 == 0):
        print(a)
    if(a<=213302):
        class1[:,i] = mat.reshape(512)
    elif(a>213302 and a<=287928):
        class2[:,i-213302] = mat.reshape(512)
    else:
        class3[:,i-287928] = mat.reshape(512)
    
np.save('class1_train',class1)
np.save('class2_train',class2)
np.save('class3_train',class3)

    



100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000
10100
10200
10300
10400
10500
10600
10700
10800
10900
11000
11100
11200
11300
11400
11500
11600
11700
11800
11900
12000
12100
12200
12300
12400
12500
12600
12700
12800
12900
13000
13100
13200
13300
13400
13500
13600
13700
13800
13900
14000
14100
14200
14300
14400
14500
14600
14700
14800
14900
15000
15100
15200
15300
15400
15500
15600
15700
15800
15900
16000
16100
16200
16300
16400
16500
16600
16700
16800
16900
17000
17100
17200
17300
17400
17500
17600
17700
17800
17900
18000
18100
18200
18300
18400
1850

133100
133200
133300
133400
133500
133600
133700
133800
133900
134000
134100
134200
134300
134400
134500
134600
134700
134800
134900
135000
135100
135200
135300
135400
135500
135600
135700
135800
135900
136000
136100
136200
136300
136400
136500
136600
136700
136800
136900
137000
137100
137200
137300
137400
137500
137600
137700
137800
137900
138000
138100
138200
138300
138400
138500
138600
138700
138800
138900
139000
139100
139200
139300
139400
139500
139600
139700
139800
139900
140000
140100
140200
140300
140400
140500
140600
140700
140800
140900
141000
141100
141200
141300
141400
141500
141600
141700
141800
141900
142000
142100
142200
142300
142400
142500
142600
142700
142800
142900
143000
143100
143200
143300
143400
143500
143600
143700
143800
143900
144000
144100
144200
144300
144400
144500
144600
144700
144800
144900
145000
145100
145200
145300
145400
145500
145600
145700
145800
145900
146000
146100
146200
146300
146400
146500
146600
146700
146800
146900
147000
147100
147200
147300

250300
250400
250500
250600
250700
250800
250900
251000
251100
251200
251300
251400
251500
251600
251700
251800
251900
252000
252100
252200
252300
252400
252500
252600
252700
252800
252900
253000
253100
253200
253300
253400
253500
253600
253700
253800
253900
254000
254100
254200
254300
254400
254500
254600
254700
254800
254900
255000
255100
255200
255300
255400
255500
255600
255700
255800
255900
256000
256100
256200
256300
256400
256500
256600
256700
256800
256900
257000
257100
257200
257300
257400
257500
257600
257700
257800
257900
258000
258100
258200
258300
258400
258500
258600
258700
258800
258900
259000
259100
259200
259300
259400
259500
259600
259700
259800
259900
260000
260100
260200
260300
260400
260500
260600
260700
260800
260900
261000
261100
261200
261300
261400
261500
261600
261700
261800
261900
262000
262100
262200
262300
262400
262500
262600
262700
262800
262900
263000
263100
263200
263300
263400
263500
263600
263700
263800
263900
264000
264100
264200
264300
264400
264500

367400
367500
367600
367700
367800
367900
368000
368100
368200
368300
368400
368500
368600
368700
368800
368900
369000
369100
369200
369300
369400
369500
369600
369700
369800
369900
370000
370100
370200
370300
370400
370500
370600
370700
370800
370900
371000
371100
371200
371300
371400
371500
371600
371700
371800
371900
372000
372100
372200
372300
372400
372500
372600
372700
372800
372900
373000
373100
373200
373300
373400
373500
373600
373700
373800
373900
374000
374100
374200
374300
374400
374500
374600
374700
374800
374900
375000
375100
375200
375300
375400
375500
375600
375700
375800
375900
376000
376100
376200
376300
376400
376500
376600
376700
376800
376900
377000
377100
377200
377300
377400
377500
377600
377700
377800
377900
378000
378100
378200
378300
378400
378500
378600
378700
378800
378900
379000
379100
379200
379300
379400
379500
379600
379700
379800
379900
380000
380100
380200
380300
380400
380500
380600
380700
380800
380900
381000
381100
381200
381300
381400
381500
381600

484500
484600
484700
484800
484900
485000
485100
485200
485300
485400
485500
485600
485700
485800
485900
486000
486100
486200
486300
486400
486500
486600
486700
486800
486900
487000
487100
487200
487300
487400
487500
487600
487700
487800
487900
488000
488100
488200
488300
488400
488500
488600
488700
488800
488900
489000
489100
489200
489300
489400
489500
489600
489700
489800
489900
490000
490100
490200
490300
490400
490500
490600
490700
490800


In [7]:
path = "/users/sairam.tabibu/outputs-18_test"

# testing - 42907, 13577, 45218
# training - 213302, 74626 , 202912
class1=np.empty((512,42907))
class2=np.empty((512,13577))
class3=np.empty((512,45218))

for i in range(101702):
    a=i+1
    if(os.path.isfile(path + '/' + str(a) + ".npy")):
        mat = np.load(path + '/' + str(a) + ".npy")
        
    if(a%100 == 0):
        print(a)
    if(a<=42907):
        class1[:,i] = mat.reshape(512)
    elif(a>42907 and a<=56484):
        class2[:,i-42907] = mat.reshape(512)
    else:
        class3[:,i-56484] = mat.reshape(512)
    
np.save('class1_test',class1)
np.save('class2_test',class2)
np.save('class3_test',class3)

    




100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000
10100
10200
10300
10400
10500
10600
10700
10800
10900
11000
11100
11200
11300
11400
11500
11600
11700
11800
11900
12000
12100
12200
12300
12400
12500
12600
12700
12800
12900
13000
13100
13200
13300
13400
13500
13600
13700
13800
13900
14000
14100
14200
14300
14400
14500
14600
14700
14800
14900
15000
15100
15200
15300
15400
15500
15600
15700
15800
15900
16000
16100
16200
16300
16400
16500
16600
16700
16800
16900
17000
17100
17200
17300
17400
17500
17600
17700
17800
17900
18000
18100
18200
18300
18400
1850

In [1]:
path = "/users/sairam.tabibu/results/kidney/subtype/resnet-18_feat/"
class1 = np.load(path+'class1_train.npy')
class2 = np.load(path+'class2_train.npy')
class3 = np.load(path+'class3_train.npy')


# testing - 42907, 13577, 45218
# training - 213302, 74626 , 202912
class1_y = np.zeros((213302))
class2_y = np.ones((74626))
class3_y = 2*np.ones((202912))


NameError: name 'np' is not defined

In [6]:
#print(np.load(path+'outputs_train/100.npy'))

In [ ]:
#classifier 1 - 1 vs 3

y_3_class = np.ones((202912))
y_1_class = np.zeros((213302))

class_13 = np.append(class1,class3,axis=1)
class_13 = class_13.T
label_13 = np.append(y_1_class,y_3_class)
print(class_13.shape)
print(label_13.shape)

clf1 = svm.LinearSVC()
clf1.fit(class_13, label_13)


In [ ]:
#classifier 2 - 1 vs 2


class_12 = np.append(class1,class2,axis=1)
class_12 = class_12.T
label_12 = np.append(class1_y,class2_y)
print(class_12.shape)
print(label_12.shape)

clf2 = svm.LinearSVC()
clf2.fit(class_12, label_12)

In [1]:
#classifier 3 - 2 vs 3

y_3_class = np.ones((202912))
y_2_class = np.zeros((74626))

class_23 = np.append(class2,class3,axis=1)
class_23 = class_23.T
label_23 = np.append(y_2_class,y_3_class)
print(class_23.shape)
print(label_23.shape)

clf3 = svm.LinearSVC()
clf3.fit(class_23, label_23)

NameError: name 'np' is not defined

In [29]:

path = "/users/sairam.tabibu/"

class1_test = np.load(path+'class1_test.npy')
class2_test = np.load(path+'class2_test.npy')
class3_test = np.load(path+'class3_test.npy')
class_123_test = np.append(class1_test,class2_test,axis=1)
class_123_test = np.append(class_123_test,class3_test,axis=1)

class_123_test = class_123_test.T

# testing - 42907, 13577, 45218
# training - 213302, 74626 , 202912
class1_test_y = np.zeros((42907))
class2_test_y = np.ones((13577))
class3_test_y = 2*np.ones((45218))

label_123_test = np.append(class1_test_y,class2_test_y)
label_123_test = np.append(label_123_test,class3_test_y)
pred_123_test = np.zeros(label_123_test.shape)

print(class_123_test.shape)
print(label_123_test.shape)


(101702, 512)
(101702,)


In [30]:
for idx in range(42907 + 13577 + 45218):
    print(idx)
    test = class_123_test[idx,:]
    label = label_123_test[idx]
    if(clf1.predict(class_123_test[idx,:].reshape(1,512)) == 0):     # 1 vs 3
        if(clf2.predict(class_123_test[idx,:].reshape(1,512)) == 0):  # 1 vs 2
            pred_123_test[idx] = 0
        else:
            pred_123_test[idx] = 1
    else:                                                             #1 vs 3
        print("hi")
        if(clf3.predict(class_123_test[idx,:].reshape(1,512)) == 0):  #2 vs 3 
            pred_123_test[idx] = 1
        else:
            pred_123_test[idx] = 2
        
    
    
    
    
    

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
hi
102
103
104
105
106
107
108
109
110
111
112
113
114
hi
115
hi
116
117
118
119
120
121
122
123
124
125
126
127
128
129
hi
130
hi
131
132
133
hi
134
135
hi
136
137
138
139
140
141
hi
142
hi
143
144
145
146
147
148
149
hi
150
151
152
153
154
155
156
hi
157
158
159
160
hi
161
hi
162
163
hi
164
hi
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
hi
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
hi

1799
1800
hi
1801
hi
1802
hi
1803
1804
1805
1806
1807
1808
1809
1810
1811
1812
hi
1813
hi
1814
1815
1816
1817
hi
1818
1819
1820
1821
1822
1823
1824
1825
hi
1826
hi
1827
hi
1828
hi
1829
1830
1831
1832
1833
1834
1835
1836
hi
1837
1838
1839
1840
1841
hi
1842
hi
1843
hi
1844
hi
1845
hi
1846
1847
1848
1849
1850
1851
1852
1853
1854
1855
1856
1857
1858
1859
hi
1860
1861
hi
1862
hi
1863
hi
1864
1865
1866
1867
1868
1869
1870
1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
hi
1881
hi
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
hi
1899
hi
1900
hi
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
hi
1918
hi
1919
hi
1920
hi
1921
hi
1922
hi
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
hi
1941
hi
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
hi
1964
hi
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977


3531
3532
3533
3534
3535
3536
3537
3538
3539
3540
3541
3542
3543
3544
3545
3546
3547
3548
3549
3550
3551
3552
3553
3554
3555
3556
3557
3558
3559
3560
3561
3562
3563
3564
3565
3566
3567
3568
3569
3570
3571
3572
3573
3574
3575
3576
3577
3578
3579
3580
3581
3582
3583
3584
3585
3586
3587
3588
3589
3590
3591
3592
3593
3594
3595
3596
3597
3598
3599
3600
3601
3602
3603
3604
3605
3606
3607
3608
3609
3610
3611
3612
3613
3614
3615
3616
3617
3618
3619
3620
3621
3622
3623
3624
3625
3626
3627
3628
3629
3630
3631
3632
3633
3634
3635
3636
3637
3638
3639
3640
3641
3642
3643
3644
3645
3646
3647
3648
3649
3650
3651
3652
3653
3654
3655
3656
3657
3658
3659
3660
3661
3662
3663
3664
3665
3666
3667
3668
3669
3670
3671
3672
3673
3674
3675
3676
3677
3678
3679
3680
3681
3682
3683
3684
3685
3686
3687
3688
3689
3690
3691
3692
3693
3694
3695
3696
3697
3698
3699
3700
3701
3702
3703
3704
3705
3706
3707
3708
3709
3710
3711
3712
3713
3714
3715
3716
3717
3718
3719
3720
3721
3722
3723
3724
3725
3726
3727
3728
3729
3730


5232
5233
5234
5235
5236
5237
5238
5239
5240
5241
5242
5243
5244
5245
5246
5247
5248
5249
5250
5251
5252
5253
5254
5255
5256
5257
5258
5259
5260
5261
5262
5263
5264
5265
5266
5267
5268
5269
5270
5271
5272
5273
5274
5275
5276
5277
5278
5279
5280
5281
5282
5283
5284
5285
5286
5287
5288
5289
5290
5291
5292
5293
5294
5295
5296
5297
5298
5299
5300
5301
5302
5303
5304
5305
5306
5307
5308
5309
5310
5311
5312
5313
5314
5315
5316
5317
5318
5319
5320
5321
5322
hi
5323
5324
5325
5326
5327
5328
5329
5330
5331
5332
5333
5334
5335
5336
5337
5338
5339
5340
5341
5342
5343
5344
5345
5346
5347
5348
5349
5350
hi
5351
5352
5353
5354
5355
5356
hi
5357
hi
5358
5359
hi
5360
hi
5361
5362
5363
5364
5365
5366
hi
5367
hi
5368
hi
5369
hi
5370
5371
5372
hi
5373
hi
5374
hi
5375
5376
5377
5378
5379
5380
hi
5381
5382
5383
5384
5385
5386
5387
5388
5389
5390
5391
5392
5393
5394
5395
5396
5397
5398
5399
5400
5401
5402
5403
5404
hi
5405
5406
5407
5408
5409
5410
5411
5412
5413
5414
5415
5416
5417
5418
5419
5420
5421
5422


6930
6931
6932
6933
6934
6935
6936
6937
6938
6939
6940
6941
6942
6943
6944
6945
6946
6947
6948
6949
6950
6951
6952
6953
6954
6955
6956
6957
6958
6959
6960
6961
6962
6963
6964
6965
6966
6967
6968
6969
6970
6971
6972
6973
6974
6975
6976
6977
6978
6979
6980
6981
6982
6983
6984
6985
6986
6987
6988
6989
6990
6991
6992
6993
6994
6995
6996
6997
6998
6999
7000
7001
7002
7003
7004
7005
7006
7007
7008
7009
7010
7011
7012
7013
7014
7015
7016
7017
7018
7019
7020
7021
7022
7023
7024
7025
7026
7027
7028
7029
7030
7031
7032
7033
7034
7035
7036
7037
7038
7039
7040
7041
7042
7043
7044
7045
7046
7047
7048
7049
7050
7051
7052
7053
7054
7055
7056
7057
7058
7059
7060
7061
7062
7063
7064
7065
7066
7067
7068
7069
7070
7071
7072
7073
7074
7075
7076
7077
7078
7079
7080
7081
7082
7083
7084
7085
7086
7087
7088
7089
7090
7091
7092
7093
7094
7095
7096
7097
7098
7099
7100
7101
7102
7103
7104
7105
7106
7107
7108
7109
7110
7111
7112
7113
7114
7115
7116
7117
7118
7119
7120
7121
7122
7123
7124
7125
7126
7127
7128
7129


8635
8636
8637
8638
8639
8640
8641
8642
8643
8644
8645
8646
8647
8648
8649
8650
8651
8652
8653
8654
8655
8656
8657
8658
8659
8660
8661
8662
8663
8664
8665
8666
8667
8668
8669
8670
8671
8672
8673
8674
8675
8676
8677
8678
8679
8680
8681
8682
8683
8684
8685
8686
8687
8688
8689
8690
8691
8692
8693
8694
8695
8696
8697
8698
8699
8700
8701
8702
8703
8704
8705
8706
8707
8708
8709
8710
8711
8712
8713
8714
8715
8716
8717
8718
8719
8720
8721
8722
8723
8724
8725
8726
8727
8728
8729
8730
8731
8732
8733
8734
8735
8736
8737
8738
8739
8740
8741
8742
8743
8744
8745
8746
8747
8748
8749
8750
8751
8752
8753
8754
8755
8756
8757
8758
8759
8760
8761
8762
8763
8764
8765
8766
8767
8768
8769
8770
8771
8772
8773
8774
8775
8776
8777
8778
8779
8780
8781
8782
8783
8784
8785
8786
8787
8788
8789
8790
8791
8792
8793
8794
8795
8796
8797
8798
8799
8800
8801
8802
8803
8804
8805
8806
8807
8808
8809
8810
8811
8812
8813
8814
8815
8816
8817
8818
8819
8820
8821
8822
8823
8824
8825
8826
8827
8828
8829
8830
8831
8832
8833
8834


10520
10521
10522
10523
10524
10525
10526
10527
10528
10529
10530
10531
10532
10533
10534
10535
10536
10537
10538
10539
10540
10541
10542
10543
10544
10545
10546
10547
10548
10549
10550
10551
10552
10553
10554
10555
10556
10557
10558
10559
10560
10561
10562
10563
10564
10565
10566
10567
10568
10569
10570
10571
10572
10573
10574
10575
10576
10577
10578
10579
10580
10581
10582
10583
10584
10585
10586
10587
hi
10588
10589
hi
10590
10591
10592
10593
10594
hi
10595
hi
10596
10597
10598
10599
10600
10601
10602
10603
10604
10605
10606
10607
10608
10609
10610
10611
10612
10613
10614
10615
10616
10617
10618
10619
10620
10621
10622
10623
10624
10625
10626
10627
10628
10629
10630
10631
10632
10633
10634
10635
10636
10637
10638
10639
10640
10641
10642
10643
10644
10645
10646
10647
10648
10649
10650
10651
10652
10653
10654
10655
10656
10657
10658
10659
10660
10661
10662
10663
10664
10665
10666
10667
10668
10669
10670
10671
10672
10673
10674
10675
10676
10677
10678
10679
10680
10681
10682
10683
hi
1

11889
hi
11890
11891
hi
11892
hi
11893
hi
11894
11895
11896
11897
11898
11899
11900
11901
11902
hi
11903
11904
hi
11905
hi
11906
11907
11908
11909
11910
11911
11912
11913
11914
11915
hi
11916
11917
11918
11919
11920
11921
11922
11923
11924
11925
hi
11926
11927
hi
11928
hi
11929
11930
11931
11932
11933
11934
11935
11936
11937
11938
11939
11940
11941
11942
11943
11944
11945
11946
hi
11947
hi
11948
hi
11949
11950
11951
hi
11952
hi
11953
11954
11955
11956
11957
hi
11958
11959
11960
11961
hi
11962
11963
11964
11965
hi
11966
11967
11968
11969
11970
11971
11972
11973
11974
hi
11975
hi
11976
11977
11978
11979
11980
11981
11982
11983
11984
hi
11985
hi
11986
hi
11987
hi
11988
11989
11990
11991
11992
hi
11993
hi
11994
hi
11995
hi
11996
hi
11997
11998
11999
12000
hi
12001
12002
12003
12004
12005
12006
12007
12008
12009
12010
12011
12012
12013
12014
12015
12016
12017
12018
12019
12020
12021
12022
12023
12024
12025
12026
12027
12028
hi
12029
hi
12030
hi
12031
hi
12032
12033
12034
12035
12036
12037
h

13276
13277
13278
13279
13280
13281
13282
13283
13284
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
hi
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
hi
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
hi
13344
hi
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
hi
13369
13370
hi
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
1343

14799
14800
14801
14802
14803
14804
14805
14806
14807
14808
14809
14810
14811
14812
14813
14814
14815
14816
14817
14818
14819
14820
14821
14822
14823
14824
14825
14826
14827
14828
14829
14830
14831
14832
14833
14834
14835
14836
14837
14838
14839
14840
14841
14842
14843
14844
14845
14846
14847
14848
14849
14850
14851
14852
14853
14854
14855
14856
14857
14858
14859
14860
14861
14862
14863
14864
14865
14866
14867
14868
14869
14870
14871
14872
14873
14874
14875
14876
14877
14878
14879
14880
14881
14882
14883
14884
14885
14886
14887
14888
14889
14890
14891
14892
14893
14894
14895
14896
14897
14898
14899
14900
14901
14902
14903
14904
14905
14906
14907
14908
14909
14910
14911
14912
14913
14914
14915
14916
14917
14918
14919
14920
14921
14922
14923
14924
14925
14926
14927
14928
14929
14930
14931
14932
14933
14934
14935
14936
14937
14938
14939
14940
14941
14942
14943
14944
14945
14946
14947
14948
14949
14950
14951
14952
14953
14954
14955
14956
14957
14958
14959
14960
14961
14962
14963
14964
1496

16284
16285
16286
16287
16288
16289
16290
16291
16292
16293
16294
16295
16296
16297
16298
16299
16300
16301
16302
16303
16304
16305
16306
16307
hi
16308
16309
16310
16311
16312
16313
16314
16315
16316
16317
16318
16319
16320
16321
16322
16323
hi
16324
16325
16326
16327
16328
hi
16329
hi
16330
16331
16332
16333
16334
16335
16336
16337
16338
16339
16340
16341
16342
16343
16344
16345
16346
16347
hi
16348
16349
16350
16351
16352
16353
16354
16355
16356
16357
16358
16359
16360
16361
16362
16363
16364
16365
16366
16367
16368
16369
16370
16371
16372
16373
16374
16375
16376
16377
16378
16379
hi
16380
16381
hi
16382
16383
16384
16385
16386
16387
16388
16389
16390
16391
16392
16393
16394
16395
16396
16397
16398
16399
16400
16401
16402
16403
16404
16405
16406
16407
16408
16409
16410
16411
16412
16413
16414
16415
16416
16417
16418
16419
hi
16420
16421
16422
16423
16424
16425
16426
16427
16428
16429
16430
16431
16432
16433
16434
16435
16436
16437
16438
16439
16440
16441
16442
16443
16444
16445
1644

17780
17781
17782
17783
17784
17785
17786
17787
17788
17789
17790
17791
17792
17793
17794
17795
17796
17797
17798
17799
17800
17801
17802
17803
hi
17804
17805
hi
17806
17807
hi
17808
17809
17810
17811
17812
17813
17814
17815
17816
17817
17818
17819
17820
17821
17822
17823
17824
17825
17826
17827
17828
17829
17830
17831
17832
hi
17833
17834
17835
17836
17837
17838
17839
17840
17841
17842
17843
17844
17845
17846
17847
17848
17849
17850
17851
17852
17853
17854
17855
17856
17857
17858
17859
17860
17861
17862
17863
17864
17865
17866
17867
17868
17869
17870
17871
17872
17873
17874
17875
17876
17877
17878
17879
17880
17881
17882
17883
17884
17885
17886
17887
17888
17889
17890
17891
17892
17893
17894
17895
17896
17897
17898
17899
17900
17901
17902
17903
17904
17905
17906
17907
17908
17909
17910
17911
17912
17913
17914
17915
17916
17917
17918
17919
17920
17921
17922
17923
17924
17925
17926
17927
17928
17929
17930
17931
17932
17933
17934
17935
17936
17937
17938
17939
17940
17941
17942
17943
1794

19107
19108
19109
19110
19111
19112
19113
19114
19115
19116
19117
19118
19119
19120
19121
19122
19123
19124
19125
19126
19127
19128
19129
19130
19131
19132
19133
19134
19135
19136
19137
19138
19139
19140
19141
19142
19143
19144
19145
19146
19147
19148
19149
19150
19151
19152
19153
19154
19155
19156
19157
19158
19159
19160
19161
19162
19163
19164
19165
19166
19167
19168
19169
19170
19171
19172
19173
19174
19175
19176
19177
19178
19179
19180
19181
19182
19183
19184
19185
19186
19187
19188
19189
19190
19191
19192
19193
19194
19195
19196
19197
19198
19199
19200
19201
19202
19203
19204
19205
19206
19207
19208
19209
19210
19211
19212
19213
19214
19215
19216
19217
19218
19219
19220
19221
19222
19223
19224
19225
19226
19227
19228
19229
19230
19231
19232
19233
19234
19235
19236
19237
19238
19239
19240
19241
19242
19243
19244
19245
19246
19247
19248
19249
19250
19251
19252
19253
19254
19255
19256
19257
19258
19259
19260
19261
19262
19263
19264
19265
19266
19267
19268
19269
19270
19271
19272
1927

20662
20663
20664
20665
20666
20667
20668
20669
20670
20671
20672
20673
20674
20675
20676
20677
20678
20679
20680
20681
20682
20683
20684
20685
20686
20687
20688
20689
20690
20691
20692
20693
20694
20695
20696
20697
20698
20699
20700
20701
20702
20703
20704
20705
20706
20707
20708
20709
20710
20711
20712
20713
20714
20715
20716
20717
20718
20719
20720
20721
20722
20723
20724
20725
20726
20727
20728
20729
20730
20731
20732
20733
20734
20735
20736
20737
20738
20739
20740
20741
20742
20743
20744
20745
20746
20747
20748
hi
20749
20750
20751
20752
20753
20754
20755
20756
20757
20758
20759
20760
20761
20762
20763
20764
20765
20766
20767
20768
20769
20770
20771
20772
20773
20774
20775
20776
20777
20778
20779
20780
20781
20782
20783
20784
20785
20786
20787
20788
20789
20790
20791
20792
20793
20794
20795
20796
20797
20798
20799
20800
20801
20802
20803
20804
20805
20806
20807
20808
hi
20809
20810
20811
20812
20813
20814
20815
20816
20817
20818
20819
20820
20821
20822
20823
20824
20825
20826
2082

22202
22203
22204
22205
22206
22207
22208
22209
22210
22211
22212
22213
hi
22214
22215
22216
hi
22217
hi
22218
22219
22220
22221
hi
22222
22223
hi
22224
22225
hi
22226
22227
hi
22228
22229
22230
hi
22231
hi
22232
22233
22234
22235
22236
22237
22238
hi
22239
hi
22240
22241
hi
22242
hi
22243
22244
22245
hi
22246
22247
22248
22249
22250
hi
22251
22252
22253
22254
hi
22255
22256
22257
22258
hi
22259
22260
hi
22261
22262
hi
22263
hi
22264
hi
22265
hi
22266
22267
22268
22269
22270
hi
22271
22272
22273
22274
hi
22275
22276
22277
22278
22279
22280
22281
hi
22282
hi
22283
22284
22285
22286
22287
22288
22289
22290
22291
22292
22293
22294
hi
22295
hi
22296
hi
22297
22298
22299
22300
hi
22301
22302
22303
22304
hi
22305
22306
22307
22308
hi
22309
22310
22311
hi
22312
22313
22314
hi
22315
hi
22316
22317
22318
hi
22319
hi
22320
22321
22322
22323
22324
22325
22326
hi
22327
hi
22328
hi
22329
22330
hi
22331
hi
22332
22333
22334
hi
22335
22336
hi
22337
hi
22338
22339
22340
22341
22342
22343
22344
hi
2234

23710
23711
23712
23713
23714
23715
23716
23717
23718
23719
23720
23721
23722
23723
23724
23725
23726
23727
23728
23729
23730
23731
23732
23733
23734
23735
23736
23737
23738
23739
23740
23741
23742
23743
23744
23745
23746
23747
23748
23749
23750
23751
23752
23753
23754
23755
23756
23757
23758
23759
23760
23761
23762
23763
23764
23765
23766
23767
23768
23769
23770
23771
23772
23773
23774
23775
23776
23777
23778
23779
23780
23781
23782
23783
23784
23785
23786
23787
23788
23789
23790
23791
23792
23793
23794
23795
23796
23797
23798
23799
23800
23801
23802
23803
23804
23805
23806
23807
23808
23809
23810
23811
23812
23813
23814
23815
23816
23817
23818
23819
23820
23821
23822
23823
23824
23825
23826
23827
23828
23829
23830
23831
23832
23833
23834
23835
23836
23837
23838
23839
23840
23841
23842
23843
23844
23845
23846
23847
23848
23849
23850
23851
23852
23853
23854
23855
23856
23857
23858
23859
23860
23861
23862
23863
23864
23865
23866
23867
23868
23869
23870
23871
23872
23873
23874
23875
2387

25353
25354
25355
25356
25357
25358
25359
25360
25361
25362
25363
25364
25365
25366
25367
25368
25369
25370
25371
25372
25373
25374
25375
25376
25377
25378
25379
25380
25381
25382
25383
25384
25385
25386
25387
25388
25389
25390
25391
25392
25393
25394
25395
25396
25397
25398
25399
25400
25401
25402
25403
25404
25405
25406
25407
25408
25409
25410
25411
25412
25413
25414
25415
25416
25417
25418
25419
25420
25421
25422
25423
25424
25425
25426
25427
25428
25429
25430
25431
25432
25433
25434
25435
25436
25437
25438
25439
25440
25441
25442
25443
25444
25445
25446
25447
25448
25449
25450
25451
25452
25453
25454
25455
25456
25457
25458
25459
25460
25461
25462
25463
25464
25465
25466
25467
25468
25469
25470
25471
25472
25473
25474
25475
25476
25477
25478
25479
25480
25481
25482
25483
25484
25485
25486
25487
25488
25489
25490
25491
25492
25493
25494
25495
25496
25497
25498
25499
25500
25501
25502
25503
25504
25505
25506
25507
25508
25509
25510
25511
25512
25513
25514
25515
25516
25517
25518
2551

27037
27038
27039
27040
27041
27042
27043
27044
27045
27046
27047
hi
27048
27049
27050
27051
27052
27053
27054
27055
27056
27057
27058
27059
hi
27060
27061
27062
27063
27064
27065
27066
27067
27068
27069
27070
27071
27072
27073
27074
27075
27076
27077
27078
27079
27080
27081
27082
hi
27083
27084
27085
27086
27087
27088
27089
27090
27091
27092
27093
27094
27095
27096
hi
27097
27098
27099
27100
27101
27102
27103
27104
27105
27106
27107
27108
27109
27110
27111
27112
27113
27114
hi
27115
27116
27117
27118
27119
27120
27121
27122
27123
27124
27125
27126
27127
27128
27129
27130
27131
27132
27133
27134
27135
27136
hi
27137
27138
hi
27139
hi
27140
27141
27142
27143
27144
27145
27146
27147
27148
27149
27150
27151
27152
27153
27154
27155
27156
27157
27158
27159
27160
27161
27162
27163
27164
27165
27166
27167
27168
27169
27170
27171
hi
27172
27173
27174
27175
27176
hi
27177
27178
27179
27180
27181
27182
27183
27184
27185
27186
27187
27188
27189
27190
27191
27192
27193
27194
27195
27196
27197
2719

28683
28684
28685
28686
28687
28688
28689
28690
28691
28692
28693
28694
28695
28696
28697
28698
28699
28700
28701
28702
28703
28704
28705
28706
28707
28708
28709
28710
28711
28712
28713
28714
28715
28716
28717
28718
28719
28720
28721
28722
28723
28724
28725
28726
28727
28728
28729
28730
28731
28732
28733
28734
28735
28736
28737
28738
28739
28740
28741
28742
28743
28744
28745
28746
28747
28748
28749
28750
28751
28752
28753
28754
28755
28756
28757
28758
28759
28760
28761
28762
28763
28764
28765
28766
28767
28768
28769
28770
28771
28772
28773
28774
28775
28776
28777
28778
28779
28780
28781
28782
28783
28784
28785
28786
28787
28788
28789
28790
28791
28792
28793
28794
28795
28796
28797
28798
28799
28800
28801
28802
28803
28804
28805
28806
28807
28808
28809
28810
28811
28812
28813
28814
28815
28816
28817
28818
28819
28820
28821
28822
28823
28824
28825
28826
28827
28828
28829
28830
28831
28832
28833
28834
28835
28836
28837
28838
28839
28840
28841
28842
28843
28844
28845
28846
28847
28848
2884

30152
30153
30154
30155
30156
30157
30158
30159
30160
30161
30162
30163
30164
30165
30166
30167
30168
30169
30170
30171
30172
30173
30174
30175
30176
30177
30178
30179
30180
30181
30182
30183
30184
30185
30186
30187
30188
30189
30190
30191
30192
30193
30194
30195
30196
30197
30198
30199
30200
30201
30202
30203
30204
30205
30206
30207
30208
30209
30210
30211
30212
30213
30214
30215
30216
30217
30218
30219
30220
30221
30222
30223
30224
30225
30226
30227
30228
30229
30230
30231
30232
30233
30234
30235
30236
30237
30238
30239
30240
30241
30242
30243
30244
30245
30246
30247
30248
30249
30250
30251
30252
30253
30254
30255
30256
30257
30258
30259
30260
30261
30262
30263
30264
30265
30266
30267
30268
30269
30270
30271
30272
30273
30274
30275
30276
30277
30278
30279
30280
30281
30282
30283
30284
30285
30286
30287
30288
30289
30290
30291
30292
30293
30294
30295
30296
30297
30298
30299
30300
30301
30302
30303
30304
30305
30306
30307
30308
30309
30310
30311
30312
30313
30314
30315
30316
30317
3031

31834
31835
31836
31837
31838
31839
31840
31841
31842
31843
31844
31845
31846
31847
31848
31849
31850
31851
31852
31853
31854
31855
31856
31857
31858
31859
31860
31861
31862
31863
31864
31865
31866
31867
31868
31869
31870
31871
31872
31873
31874
31875
31876
31877
31878
31879
31880
31881
31882
31883
31884
31885
31886
31887
31888
31889
31890
31891
31892
31893
31894
31895
31896
31897
31898
31899
31900
31901
31902
31903
31904
31905
31906
31907
31908
31909
31910
31911
31912
31913
31914
31915
31916
31917
31918
31919
31920
31921
31922
31923
31924
31925
31926
31927
31928
31929
31930
31931
31932
31933
31934
31935
31936
31937
31938
31939
31940
31941
31942
31943
31944
31945
31946
31947
31948
31949
31950
31951
31952
31953
31954
31955
31956
31957
31958
31959
31960
31961
31962
31963
31964
31965
31966
31967
31968
31969
31970
31971
31972
31973
31974
31975
31976
31977
31978
31979
31980
31981
31982
31983
31984
31985
31986
31987
31988
31989
31990
31991
31992
31993
31994
31995
31996
31997
31998
31999
3200

33519
33520
33521
33522
33523
33524
33525
33526
33527
33528
33529
33530
33531
33532
33533
33534
33535
33536
33537
33538
33539
33540
33541
33542
33543
33544
33545
33546
33547
33548
33549
33550
33551
33552
33553
33554
33555
33556
33557
33558
33559
33560
33561
33562
33563
33564
33565
33566
33567
33568
33569
33570
33571
33572
33573
33574
33575
33576
33577
33578
33579
33580
33581
33582
33583
33584
33585
33586
33587
33588
33589
33590
33591
33592
33593
33594
33595
33596
33597
33598
33599
33600
33601
33602
33603
33604
33605
33606
33607
33608
33609
33610
33611
33612
33613
33614
33615
33616
33617
33618
33619
33620
33621
33622
33623
33624
33625
33626
33627
33628
33629
33630
33631
33632
33633
33634
33635
33636
33637
33638
33639
33640
33641
33642
33643
33644
33645
33646
33647
33648
33649
33650
33651
33652
33653
33654
33655
33656
33657
33658
33659
33660
33661
33662
33663
hi
33664
33665
33666
33667
33668
33669
33670
33671
33672
33673
33674
33675
33676
33677
33678
33679
33680
33681
33682
33683
33684
3

35202
35203
35204
35205
35206
35207
35208
35209
35210
35211
35212
35213
35214
35215
35216
35217
35218
35219
35220
35221
35222
35223
35224
35225
35226
35227
35228
35229
35230
35231
35232
35233
35234
35235
35236
35237
35238
35239
35240
35241
35242
35243
35244
35245
35246
35247
35248
35249
35250
35251
35252
35253
35254
35255
35256
35257
35258
35259
35260
35261
35262
35263
35264
35265
35266
35267
35268
35269
35270
35271
35272
35273
35274
35275
35276
35277
35278
35279
35280
35281
35282
35283
35284
35285
35286
35287
35288
35289
35290
35291
35292
35293
35294
35295
35296
35297
35298
35299
35300
35301
35302
35303
35304
35305
35306
35307
35308
35309
35310
35311
35312
35313
35314
35315
35316
35317
35318
35319
35320
35321
35322
35323
35324
35325
35326
35327
35328
35329
35330
35331
35332
35333
35334
35335
35336
35337
35338
35339
35340
35341
35342
35343
35344
35345
35346
35347
35348
35349
35350
35351
35352
35353
35354
35355
35356
35357
35358
35359
35360
35361
35362
35363
35364
35365
35366
35367
3536

36862
36863
36864
36865
36866
36867
36868
36869
36870
36871
36872
36873
36874
36875
36876
36877
36878
36879
36880
36881
36882
36883
36884
36885
36886
36887
36888
36889
36890
36891
36892
36893
36894
36895
36896
36897
36898
36899
36900
36901
36902
36903
36904
36905
36906
36907
36908
36909
36910
36911
36912
36913
36914
36915
36916
36917
36918
36919
36920
36921
36922
36923
36924
36925
36926
36927
36928
36929
36930
36931
36932
36933
36934
36935
36936
36937
36938
36939
36940
36941
36942
36943
36944
36945
36946
36947
36948
36949
36950
36951
36952
36953
36954
36955
36956
36957
36958
36959
36960
36961
36962
36963
36964
36965
36966
36967
36968
36969
36970
36971
36972
36973
36974
36975
36976
36977
36978
36979
36980
36981
36982
36983
36984
36985
36986
36987
36988
36989
36990
36991
36992
36993
36994
36995
36996
36997
36998
36999
37000
37001
37002
37003
37004
37005
37006
37007
37008
37009
37010
37011
37012
37013
37014
37015
37016
37017
37018
37019
37020
37021
37022
37023
37024
37025
37026
37027
3702

38492
38493
38494
38495
38496
38497
38498
38499
38500
38501
38502
38503
38504
38505
38506
38507
38508
38509
38510
38511
38512
38513
38514
38515
38516
38517
38518
38519
38520
38521
38522
38523
38524
38525
38526
38527
38528
38529
38530
38531
38532
38533
38534
38535
38536
38537
38538
38539
38540
38541
38542
38543
38544
38545
38546
38547
38548
38549
38550
38551
38552
38553
38554
38555
38556
38557
38558
38559
38560
38561
38562
38563
38564
38565
38566
38567
38568
38569
38570
38571
38572
38573
38574
38575
38576
38577
38578
38579
38580
38581
38582
38583
38584
38585
38586
38587
38588
38589
38590
38591
38592
38593
38594
38595
38596
38597
38598
38599
38600
38601
38602
38603
38604
38605
38606
38607
38608
38609
38610
38611
38612
38613
38614
38615
38616
38617
38618
38619
38620
38621
38622
38623
38624
38625
38626
38627
38628
38629
38630
38631
38632
38633
38634
38635
38636
38637
38638
38639
38640
38641
38642
38643
38644
38645
38646
38647
38648
38649
38650
38651
38652
38653
38654
38655
38656
38657
3865

40109
40110
40111
40112
40113
40114
40115
40116
40117
40118
40119
40120
40121
40122
40123
40124
40125
40126
40127
40128
40129
40130
40131
40132
40133
40134
40135
40136
40137
40138
40139
40140
40141
40142
40143
40144
40145
40146
40147
40148
40149
40150
40151
40152
40153
40154
40155
40156
40157
40158
40159
40160
40161
40162
40163
40164
40165
40166
40167
40168
40169
40170
40171
40172
40173
40174
40175
40176
40177
40178
40179
40180
40181
40182
40183
40184
40185
40186
40187
40188
40189
40190
40191
40192
40193
40194
40195
40196
40197
40198
40199
40200
40201
40202
40203
40204
40205
40206
40207
40208
40209
40210
40211
40212
40213
40214
40215
40216
40217
40218
40219
40220
40221
40222
40223
40224
40225
40226
40227
40228
40229
40230
40231
40232
40233
40234
40235
40236
40237
40238
40239
40240
40241
40242
40243
40244
40245
40246
40247
40248
40249
40250
40251
40252
40253
40254
40255
40256
40257
40258
40259
40260
40261
40262
40263
40264
40265
40266
hi
40267
40268
40269
40270
40271
40272
40273
40274
4

41752
41753
41754
41755
41756
41757
41758
41759
41760
41761
41762
41763
41764
41765
41766
41767
41768
41769
41770
41771
41772
41773
41774
41775
41776
41777
41778
41779
41780
41781
41782
41783
41784
41785
41786
41787
41788
41789
41790
41791
41792
41793
41794
41795
41796
41797
41798
41799
41800
41801
41802
41803
41804
41805
41806
41807
41808
41809
41810
41811
41812
41813
hi
41814
41815
41816
hi
41817
41818
41819
41820
41821
41822
41823
41824
41825
41826
41827
41828
41829
41830
41831
41832
41833
41834
41835
41836
41837
41838
41839
41840
41841
41842
41843
41844
41845
41846
41847
41848
41849
41850
41851
41852
41853
41854
hi
41855
41856
41857
41858
41859
41860
41861
41862
41863
41864
41865
41866
41867
41868
41869
41870
41871
41872
41873
41874
41875
41876
41877
41878
41879
41880
41881
41882
41883
41884
41885
41886
41887
41888
41889
41890
41891
41892
41893
41894
41895
41896
41897
41898
41899
41900
41901
41902
41903
41904
41905
41906
41907
41908
41909
41910
41911
41912
41913
41914
41915
41916
4

43357
hi
43358
43359
43360
43361
43362
43363
hi
43364
hi
43365
hi
43366
hi
43367
43368
43369
43370
43371
43372
hi
43373
43374
43375
hi
43376
hi
43377
43378
43379
43380
43381
43382
43383
43384
43385
hi
43386
hi
43387
43388
43389
hi
43390
43391
43392
43393
43394
43395
43396
43397
43398
43399
hi
43400
hi
43401
hi
43402
hi
43403
hi
43404
hi
43405
43406
43407
43408
43409
43410
43411
43412
hi
43413
43414
43415
43416
43417
43418
hi
43419
hi
43420
hi
43421
hi
43422
hi
43423
hi
43424
hi
43425
43426
43427
43428
43429
43430
43431
43432
43433
43434
43435
hi
43436
hi
43437
hi
43438
hi
43439
hi
43440
hi
43441
hi
43442
43443
43444
43445
43446
43447
43448
43449
43450
43451
43452
hi
43453
hi
43454
hi
43455
hi
43456
hi
43457
43458
43459
43460
43461
43462
43463
43464
43465
43466
hi
43467
hi
43468
hi
43469
hi
43470
43471
43472
43473
43474
43475
43476
43477
43478
hi
43479
43480
hi
43481
43482
43483
43484
hi
43485
43486
43487
43488
hi
43489
43490
43491
43492
43493
43494
43495
43496
43497
43498
43499
43500
4

44765
hi
44766
44767
44768
hi
44769
hi
44770
hi
44771
44772
44773
44774
44775
44776
44777
44778
44779
44780
44781
44782
44783
44784
44785
44786
hi
44787
44788
hi
44789
hi
44790
44791
44792
44793
44794
44795
44796
hi
44797
hi
44798
44799
44800
hi
44801
hi
44802
hi
44803
hi
44804
44805
44806
44807
44808
44809
44810
hi
44811
44812
44813
44814
44815
44816
hi
44817
hi
44818
44819
44820
hi
44821
hi
44822
44823
44824
44825
44826
44827
44828
44829
44830
44831
44832
hi
44833
44834
44835
hi
44836
hi
44837
hi
44838
hi
44839
44840
44841
44842
44843
44844
44845
44846
hi
44847
44848
44849
hi
44850
hi
44851
44852
44853
44854
hi
44855
hi
44856
44857
44858
44859
44860
44861
44862
44863
44864
44865
44866
44867
44868
hi
44869
hi
44870
hi
44871
hi
44872
44873
44874
44875
44876
44877
44878
hi
44879
hi
44880
44881
44882
44883
44884
44885
44886
44887
44888
44889
44890
44891
44892
44893
44894
44895
44896
44897
44898
44899
hi
44900
hi
44901
hi
44902
hi
44903
44904
44905
44906
44907
44908
44909
44910
hi
44911
h

hi
46288
46289
46290
46291
46292
46293
46294
46295
hi
46296
hi
46297
hi
46298
46299
46300
46301
46302
46303
46304
46305
46306
46307
46308
46309
hi
46310
hi
46311
hi
46312
hi
46313
hi
46314
hi
46315
hi
46316
hi
46317
hi
46318
hi
46319
hi
46320
hi
46321
hi
46322
46323
hi
46324
46325
46326
46327
46328
hi
46329
46330
46331
46332
46333
46334
46335
46336
46337
46338
46339
46340
46341
46342
46343
hi
46344
hi
46345
hi
46346
hi
46347
hi
46348
46349
hi
46350
hi
46351
hi
46352
hi
46353
hi
46354
46355
46356
46357
46358
46359
46360
46361
46362
46363
46364
46365
46366
hi
46367
hi
46368
hi
46369
hi
46370
hi
46371
hi
46372
hi
46373
hi
46374
hi
46375
hi
46376
hi
46377
46378
hi
46379
46380
46381
46382
46383
46384
46385
46386
46387
46388
46389
46390
46391
46392
46393
46394
46395
46396
46397
46398
hi
46399
46400
46401
46402
46403
hi
46404
hi
46405
46406
hi
46407
46408
46409
46410
46411
hi
46412
46413
hi
46414
hi
46415
hi
46416
hi
46417
hi
46418
46419
46420
hi
46421
hi
46422
hi
46423
hi
46424
46425
hi
4642

47775
47776
hi
47777
47778
47779
47780
47781
47782
47783
47784
hi
47785
47786
47787
47788
47789
47790
47791
47792
47793
47794
47795
47796
hi
47797
47798
hi
47799
hi
47800
hi
47801
hi
47802
hi
47803
hi
47804
47805
47806
47807
hi
47808
hi
47809
hi
47810
hi
47811
hi
47812
hi
47813
hi
47814
hi
47815
hi
47816
hi
47817
hi
47818
hi
47819
hi
47820
47821
47822
hi
47823
hi
47824
hi
47825
hi
47826
hi
47827
47828
47829
47830
47831
47832
hi
47833
hi
47834
47835
47836
47837
47838
47839
47840
47841
47842
47843
47844
47845
hi
47846
47847
47848
47849
47850
hi
47851
hi
47852
hi
47853
hi
47854
hi
47855
hi
47856
47857
47858
hi
47859
hi
47860
hi
47861
hi
47862
47863
hi
47864
hi
47865
hi
47866
hi
47867
hi
47868
47869
47870
hi
47871
hi
47872
hi
47873
47874
47875
hi
47876
hi
47877
hi
47878
hi
47879
hi
47880
hi
47881
47882
47883
47884
47885
47886
47887
47888
47889
47890
47891
hi
47892
47893
47894
47895
47896
47897
47898
47899
47900
47901
47902
47903
47904
47905
47906
47907
hi
47908
hi
47909
hi
47910
hi
47911
h

hi
49242
hi
49243
49244
hi
49245
hi
49246
hi
49247
49248
hi
49249
49250
49251
hi
49252
hi
49253
hi
49254
hi
49255
hi
49256
hi
49257
hi
49258
hi
49259
hi
49260
hi
49261
hi
49262
hi
49263
hi
49264
49265
hi
49266
hi
49267
hi
49268
hi
49269
hi
49270
hi
49271
hi
49272
hi
49273
hi
49274
hi
49275
hi
49276
hi
49277
49278
hi
49279
hi
49280
hi
49281
hi
49282
hi
49283
hi
49284
hi
49285
hi
49286
hi
49287
hi
49288
hi
49289
hi
49290
hi
49291
hi
49292
hi
49293
hi
49294
hi
49295
hi
49296
hi
49297
hi
49298
49299
hi
49300
hi
49301
hi
49302
hi
49303
hi
49304
49305
hi
49306
hi
49307
hi
49308
hi
49309
hi
49310
49311
hi
49312
hi
49313
hi
49314
hi
49315
hi
49316
hi
49317
hi
49318
hi
49319
hi
49320
hi
49321
hi
49322
hi
49323
49324
hi
49325
hi
49326
hi
49327
hi
49328
49329
hi
49330
hi
49331
hi
49332
hi
49333
hi
49334
hi
49335
hi
49336
hi
49337
hi
49338
hi
49339
hi
49340
hi
49341
hi
49342
hi
49343
hi
49344
hi
49345
49346
49347
hi
49348
49349
hi
49350
hi
49351
49352
hi
49353
hi
49354
49355
hi
49356
49357
hi
4935

50710
50711
50712
50713
50714
50715
50716
50717
50718
50719
50720
50721
50722
50723
50724
50725
50726
50727
hi
50728
hi
50729
hi
50730
50731
50732
50733
50734
50735
50736
50737
50738
50739
50740
50741
50742
50743
50744
50745
hi
50746
50747
50748
50749
50750
50751
hi
50752
50753
50754
50755
hi
50756
50757
50758
50759
50760
50761
50762
50763
50764
50765
50766
50767
50768
50769
50770
50771
50772
50773
50774
50775
50776
50777
50778
50779
50780
50781
50782
50783
50784
50785
50786
50787
hi
50788
50789
50790
50791
50792
50793
50794
50795
50796
hi
50797
50798
50799
50800
50801
50802
50803
50804
50805
50806
hi
50807
50808
50809
50810
50811
50812
hi
50813
50814
50815
50816
50817
50818
50819
50820
50821
50822
50823
50824
50825
50826
50827
50828
50829
50830
50831
50832
50833
50834
50835
50836
50837
50838
50839
50840
50841
50842
50843
50844
50845
50846
50847
50848
50849
50850
50851
50852
50853
50854
50855
50856
50857
50858
50859
50860
50861
50862
50863
50864
50865
50866
50867
50868
50869
50870
5087

52064
52065
hi
52066
hi
52067
hi
52068
hi
52069
hi
52070
hi
52071
hi
52072
hi
52073
hi
52074
hi
52075
hi
52076
hi
52077
hi
52078
hi
52079
hi
52080
hi
52081
hi
52082
hi
52083
hi
52084
hi
52085
hi
52086
hi
52087
hi
52088
hi
52089
hi
52090
hi
52091
hi
52092
hi
52093
hi
52094
hi
52095
hi
52096
hi
52097
hi
52098
hi
52099
hi
52100
hi
52101
hi
52102
hi
52103
hi
52104
hi
52105
hi
52106
hi
52107
hi
52108
hi
52109
52110
hi
52111
hi
52112
hi
52113
hi
52114
hi
52115
hi
52116
hi
52117
hi
52118
hi
52119
hi
52120
hi
52121
hi
52122
52123
52124
52125
52126
52127
hi
52128
hi
52129
hi
52130
hi
52131
hi
52132
hi
52133
hi
52134
hi
52135
hi
52136
hi
52137
hi
52138
52139
hi
52140
hi
52141
hi
52142
hi
52143
hi
52144
hi
52145
hi
52146
hi
52147
hi
52148
52149
52150
52151
52152
hi
52153
52154
hi
52155
hi
52156
hi
52157
hi
52158
52159
52160
hi
52161
hi
52162
hi
52163
hi
52164
hi
52165
hi
52166
52167
52168
52169
hi
52170
hi
52171
hi
52172
hi
52173
hi
52174
hi
52175
hi
52176
52177
hi
52178
hi
52179
hi
52180
52181
5

hi
53371
hi
53372
hi
53373
hi
53374
hi
53375
hi
53376
hi
53377
hi
53378
hi
53379
hi
53380
hi
53381
hi
53382
hi
53383
hi
53384
53385
53386
53387
53388
53389
53390
53391
53392
53393
53394
53395
53396
53397
53398
53399
53400
53401
53402
hi
53403
hi
53404
hi
53405
53406
hi
53407
hi
53408
53409
hi
53410
53411
53412
53413
53414
53415
53416
53417
hi
53418
hi
53419
53420
53421
53422
hi
53423
53424
53425
hi
53426
hi
53427
hi
53428
hi
53429
hi
53430
hi
53431
hi
53432
hi
53433
hi
53434
hi
53435
hi
53436
hi
53437
hi
53438
hi
53439
hi
53440
53441
hi
53442
hi
53443
hi
53444
53445
hi
53446
53447
53448
53449
53450
53451
53452
53453
53454
53455
53456
53457
53458
hi
53459
hi
53460
53461
53462
53463
53464
53465
hi
53466
hi
53467
hi
53468
hi
53469
hi
53470
hi
53471
hi
53472
hi
53473
hi
53474
hi
53475
hi
53476
hi
53477
hi
53478
hi
53479
hi
53480
53481
hi
53482
53483
hi
53484
hi
53485
53486
53487
hi
53488
hi
53489
53490
53491
hi
53492
53493
hi
53494
53495
53496
53497
hi
53498
hi
53499
hi
53500
hi
53501
hi
5

54653
hi
54654
hi
54655
hi
54656
hi
54657
hi
54658
hi
54659
hi
54660
hi
54661
hi
54662
hi
54663
hi
54664
hi
54665
hi
54666
hi
54667
hi
54668
hi
54669
hi
54670
hi
54671
hi
54672
hi
54673
hi
54674
hi
54675
hi
54676
hi
54677
hi
54678
hi
54679
hi
54680
hi
54681
hi
54682
hi
54683
hi
54684
hi
54685
hi
54686
hi
54687
hi
54688
hi
54689
hi
54690
hi
54691
hi
54692
hi
54693
hi
54694
hi
54695
hi
54696
hi
54697
hi
54698
hi
54699
hi
54700
hi
54701
hi
54702
hi
54703
hi
54704
hi
54705
hi
54706
hi
54707
hi
54708
hi
54709
hi
54710
hi
54711
hi
54712
hi
54713
hi
54714
hi
54715
hi
54716
hi
54717
hi
54718
hi
54719
hi
54720
hi
54721
hi
54722
hi
54723
hi
54724
hi
54725
hi
54726
hi
54727
hi
54728
hi
54729
hi
54730
hi
54731
hi
54732
hi
54733
hi
54734
hi
54735
hi
54736
hi
54737
hi
54738
hi
54739
hi
54740
hi
54741
hi
54742
hi
54743
hi
54744
hi
54745
hi
54746
hi
54747
hi
54748
hi
54749
hi
54750
hi
54751
hi
54752
hi
54753
hi
54754
hi
54755
hi
54756
hi
54757
hi
54758
hi
54759
hi
54760
hi
54761
hi
54762
hi
54763
hi
5

55819
55820
55821
55822
55823
55824
55825
55826
55827
55828
55829
55830
55831
55832
55833
hi
55834
55835
55836
55837
55838
55839
55840
55841
55842
55843
hi
55844
55845
55846
hi
55847
55848
55849
55850
55851
55852
55853
55854
55855
55856
55857
55858
55859
55860
55861
55862
55863
55864
55865
55866
hi
55867
55868
55869
55870
55871
55872
55873
55874
55875
55876
55877
55878
55879
55880
55881
55882
55883
55884
55885
55886
55887
55888
55889
55890
55891
hi
55892
55893
55894
55895
hi
55896
hi
55897
55898
hi
55899
hi
55900
55901
55902
55903
55904
55905
hi
55906
hi
55907
hi
55908
hi
55909
hi
55910
55911
55912
55913
55914
55915
55916
55917
hi
55918
hi
55919
hi
55920
hi
55921
hi
55922
hi
55923
hi
55924
hi
55925
hi
55926
hi
55927
55928
55929
55930
55931
55932
55933
55934
55935
55936
55937
hi
55938
55939
hi
55940
hi
55941
hi
55942
hi
55943
hi
55944
hi
55945
hi
55946
hi
55947
hi
55948
hi
55949
hi
55950
hi
55951
55952
55953
55954
55955
55956
55957
55958
55959
55960
55961
55962
hi
55963
55964
hi
55965
5

hi
57088
hi
57089
hi
57090
hi
57091
hi
57092
hi
57093
hi
57094
hi
57095
hi
57096
hi
57097
hi
57098
hi
57099
57100
hi
57101
hi
57102
hi
57103
hi
57104
hi
57105
hi
57106
hi
57107
hi
57108
hi
57109
hi
57110
hi
57111
hi
57112
hi
57113
hi
57114
hi
57115
hi
57116
hi
57117
hi
57118
hi
57119
hi
57120
hi
57121
hi
57122
hi
57123
57124
57125
57126
hi
57127
hi
57128
hi
57129
hi
57130
hi
57131
hi
57132
hi
57133
hi
57134
hi
57135
hi
57136
hi
57137
hi
57138
hi
57139
hi
57140
hi
57141
hi
57142
hi
57143
hi
57144
hi
57145
hi
57146
hi
57147
hi
57148
hi
57149
hi
57150
hi
57151
hi
57152
hi
57153
hi
57154
hi
57155
hi
57156
hi
57157
hi
57158
hi
57159
hi
57160
hi
57161
hi
57162
hi
57163
hi
57164
hi
57165
hi
57166
hi
57167
hi
57168
57169
hi
57170
hi
57171
hi
57172
hi
57173
hi
57174
hi
57175
hi
57176
hi
57177
hi
57178
hi
57179
hi
57180
hi
57181
hi
57182
hi
57183
hi
57184
hi
57185
hi
57186
hi
57187
hi
57188
hi
57189
hi
57190
hi
57191
hi
57192
hi
57193
hi
57194
hi
57195
hi
57196
hi
57197
hi
57198
hi
57199
hi
5720

hi
58217
hi
58218
58219
58220
58221
hi
58222
hi
58223
hi
58224
hi
58225
hi
58226
hi
58227
hi
58228
hi
58229
hi
58230
hi
58231
hi
58232
hi
58233
hi
58234
hi
58235
hi
58236
hi
58237
hi
58238
hi
58239
hi
58240
hi
58241
hi
58242
hi
58243
hi
58244
hi
58245
hi
58246
hi
58247
hi
58248
hi
58249
hi
58250
hi
58251
hi
58252
hi
58253
hi
58254
hi
58255
hi
58256
hi
58257
hi
58258
hi
58259
hi
58260
hi
58261
hi
58262
hi
58263
hi
58264
hi
58265
hi
58266
hi
58267
hi
58268
hi
58269
hi
58270
hi
58271
hi
58272
hi
58273
hi
58274
hi
58275
hi
58276
hi
58277
hi
58278
hi
58279
hi
58280
hi
58281
hi
58282
hi
58283
hi
58284
hi
58285
58286
hi
58287
hi
58288
58289
58290
hi
58291
hi
58292
hi
58293
hi
58294
hi
58295
hi
58296
hi
58297
hi
58298
hi
58299
hi
58300
hi
58301
hi
58302
hi
58303
hi
58304
hi
58305
hi
58306
hi
58307
hi
58308
hi
58309
hi
58310
hi
58311
hi
58312
hi
58313
hi
58314
hi
58315
hi
58316
hi
58317
hi
58318
hi
58319
hi
58320
hi
58321
hi
58322
hi
58323
hi
58324
hi
58325
hi
58326
hi
58327
hi
58328
hi
58329
h

hi
59336
hi
59337
hi
59338
hi
59339
hi
59340
hi
59341
hi
59342
hi
59343
hi
59344
hi
59345
hi
59346
hi
59347
hi
59348
hi
59349
hi
59350
hi
59351
hi
59352
hi
59353
hi
59354
hi
59355
hi
59356
hi
59357
59358
hi
59359
hi
59360
hi
59361
hi
59362
hi
59363
hi
59364
hi
59365
hi
59366
hi
59367
hi
59368
hi
59369
hi
59370
hi
59371
hi
59372
hi
59373
hi
59374
hi
59375
hi
59376
hi
59377
hi
59378
hi
59379
hi
59380
hi
59381
hi
59382
hi
59383
hi
59384
hi
59385
hi
59386
hi
59387
hi
59388
hi
59389
hi
59390
hi
59391
hi
59392
hi
59393
hi
59394
hi
59395
hi
59396
hi
59397
hi
59398
hi
59399
hi
59400
hi
59401
hi
59402
hi
59403
hi
59404
hi
59405
hi
59406
hi
59407
hi
59408
hi
59409
hi
59410
hi
59411
hi
59412
hi
59413
hi
59414
hi
59415
hi
59416
hi
59417
hi
59418
hi
59419
hi
59420
hi
59421
hi
59422
hi
59423
hi
59424
hi
59425
hi
59426
hi
59427
hi
59428
hi
59429
hi
59430
hi
59431
hi
59432
hi
59433
hi
59434
hi
59435
hi
59436
hi
59437
hi
59438
hi
59439
hi
59440
hi
59441
hi
59442
59443
hi
59444
hi
59445
hi
59446
hi
5944

hi
60443
hi
60444
hi
60445
hi
60446
60447
hi
60448
hi
60449
hi
60450
hi
60451
hi
60452
hi
60453
hi
60454
hi
60455
hi
60456
hi
60457
hi
60458
hi
60459
hi
60460
hi
60461
hi
60462
hi
60463
hi
60464
hi
60465
hi
60466
hi
60467
hi
60468
hi
60469
hi
60470
hi
60471
hi
60472
hi
60473
hi
60474
hi
60475
hi
60476
hi
60477
hi
60478
hi
60479
hi
60480
hi
60481
hi
60482
hi
60483
hi
60484
hi
60485
hi
60486
hi
60487
60488
hi
60489
hi
60490
hi
60491
hi
60492
hi
60493
hi
60494
hi
60495
60496
hi
60497
hi
60498
hi
60499
hi
60500
hi
60501
hi
60502
hi
60503
hi
60504
hi
60505
hi
60506
hi
60507
hi
60508
hi
60509
hi
60510
hi
60511
hi
60512
hi
60513
hi
60514
hi
60515
hi
60516
hi
60517
hi
60518
hi
60519
hi
60520
hi
60521
hi
60522
hi
60523
hi
60524
hi
60525
hi
60526
hi
60527
hi
60528
hi
60529
hi
60530
hi
60531
hi
60532
hi
60533
hi
60534
hi
60535
hi
60536
hi
60537
hi
60538
hi
60539
hi
60540
hi
60541
hi
60542
hi
60543
hi
60544
hi
60545
hi
60546
hi
60547
hi
60548
hi
60549
hi
60550
hi
60551
hi
60552
hi
60553
hi
60554
h

hi
61557
hi
61558
hi
61559
hi
61560
hi
61561
hi
61562
hi
61563
hi
61564
hi
61565
hi
61566
hi
61567
hi
61568
hi
61569
hi
61570
hi
61571
hi
61572
hi
61573
hi
61574
hi
61575
hi
61576
hi
61577
hi
61578
hi
61579
hi
61580
hi
61581
hi
61582
hi
61583
hi
61584
hi
61585
hi
61586
hi
61587
hi
61588
hi
61589
hi
61590
hi
61591
hi
61592
hi
61593
hi
61594
hi
61595
hi
61596
hi
61597
hi
61598
hi
61599
hi
61600
hi
61601
hi
61602
hi
61603
hi
61604
hi
61605
hi
61606
hi
61607
hi
61608
hi
61609
hi
61610
hi
61611
hi
61612
hi
61613
hi
61614
hi
61615
hi
61616
hi
61617
hi
61618
hi
61619
hi
61620
hi
61621
hi
61622
hi
61623
hi
61624
hi
61625
hi
61626
hi
61627
hi
61628
hi
61629
hi
61630
hi
61631
hi
61632
hi
61633
hi
61634
hi
61635
hi
61636
hi
61637
hi
61638
hi
61639
hi
61640
hi
61641
hi
61642
hi
61643
hi
61644
hi
61645
hi
61646
hi
61647
hi
61648
hi
61649
hi
61650
hi
61651
hi
61652
hi
61653
hi
61654
hi
61655
hi
61656
hi
61657
hi
61658
hi
61659
hi
61660
hi
61661
hi
61662
hi
61663
hi
61664
hi
61665
hi
61666
hi
61667
h

hi
62669
hi
62670
hi
62671
hi
62672
hi
62673
hi
62674
hi
62675
hi
62676
hi
62677
hi
62678
hi
62679
hi
62680
hi
62681
hi
62682
hi
62683
hi
62684
hi
62685
hi
62686
hi
62687
hi
62688
hi
62689
hi
62690
hi
62691
hi
62692
hi
62693
hi
62694
hi
62695
hi
62696
hi
62697
hi
62698
hi
62699
hi
62700
hi
62701
hi
62702
hi
62703
hi
62704
hi
62705
hi
62706
hi
62707
hi
62708
62709
62710
62711
62712
62713
62714
hi
62715
hi
62716
hi
62717
hi
62718
hi
62719
hi
62720
hi
62721
hi
62722
hi
62723
hi
62724
hi
62725
hi
62726
hi
62727
hi
62728
hi
62729
hi
62730
hi
62731
hi
62732
hi
62733
hi
62734
hi
62735
hi
62736
hi
62737
hi
62738
hi
62739
hi
62740
hi
62741
hi
62742
hi
62743
hi
62744
hi
62745
hi
62746
hi
62747
hi
62748
hi
62749
hi
62750
hi
62751
hi
62752
hi
62753
62754
hi
62755
hi
62756
hi
62757
hi
62758
hi
62759
hi
62760
hi
62761
hi
62762
hi
62763
hi
62764
hi
62765
hi
62766
hi
62767
hi
62768
hi
62769
hi
62770
hi
62771
hi
62772
hi
62773
hi
62774
hi
62775
hi
62776
hi
62777
hi
62778
hi
62779
hi
62780
hi
62781
hi
6

63778
hi
63779
hi
63780
hi
63781
hi
63782
hi
63783
hi
63784
hi
63785
hi
63786
hi
63787
hi
63788
hi
63789
hi
63790
hi
63791
hi
63792
hi
63793
hi
63794
hi
63795
hi
63796
hi
63797
hi
63798
hi
63799
hi
63800
hi
63801
hi
63802
hi
63803
hi
63804
hi
63805
hi
63806
hi
63807
hi
63808
hi
63809
hi
63810
hi
63811
hi
63812
hi
63813
hi
63814
hi
63815
hi
63816
hi
63817
hi
63818
hi
63819
hi
63820
hi
63821
63822
hi
63823
hi
63824
hi
63825
hi
63826
hi
63827
hi
63828
hi
63829
hi
63830
hi
63831
hi
63832
hi
63833
hi
63834
hi
63835
hi
63836
hi
63837
hi
63838
hi
63839
hi
63840
hi
63841
hi
63842
hi
63843
hi
63844
hi
63845
hi
63846
hi
63847
hi
63848
hi
63849
hi
63850
hi
63851
hi
63852
hi
63853
hi
63854
hi
63855
hi
63856
hi
63857
hi
63858
hi
63859
hi
63860
hi
63861
hi
63862
hi
63863
hi
63864
hi
63865
hi
63866
hi
63867
hi
63868
hi
63869
hi
63870
hi
63871
hi
63872
hi
63873
hi
63874
hi
63875
hi
63876
hi
63877
hi
63878
hi
63879
hi
63880
hi
63881
hi
63882
hi
63883
hi
63884
hi
63885
hi
63886
hi
63887
hi
63888
hi
6388

64874
hi
64875
hi
64876
hi
64877
hi
64878
hi
64879
hi
64880
hi
64881
hi
64882
hi
64883
hi
64884
hi
64885
hi
64886
hi
64887
hi
64888
hi
64889
hi
64890
hi
64891
hi
64892
hi
64893
hi
64894
hi
64895
hi
64896
hi
64897
hi
64898
hi
64899
hi
64900
hi
64901
hi
64902
hi
64903
hi
64904
hi
64905
hi
64906
hi
64907
hi
64908
hi
64909
hi
64910
hi
64911
64912
hi
64913
hi
64914
hi
64915
hi
64916
hi
64917
hi
64918
hi
64919
hi
64920
hi
64921
hi
64922
hi
64923
hi
64924
hi
64925
hi
64926
hi
64927
hi
64928
hi
64929
hi
64930
hi
64931
hi
64932
hi
64933
hi
64934
hi
64935
hi
64936
hi
64937
hi
64938
hi
64939
hi
64940
hi
64941
hi
64942
hi
64943
hi
64944
hi
64945
hi
64946
hi
64947
hi
64948
hi
64949
hi
64950
hi
64951
hi
64952
hi
64953
hi
64954
hi
64955
hi
64956
hi
64957
hi
64958
hi
64959
hi
64960
hi
64961
hi
64962
hi
64963
hi
64964
hi
64965
hi
64966
hi
64967
hi
64968
hi
64969
hi
64970
hi
64971
hi
64972
hi
64973
hi
64974
hi
64975
hi
64976
hi
64977
hi
64978
hi
64979
hi
64980
hi
64981
hi
64982
hi
64983
hi
64984
hi
6498

65959
hi
65960
hi
65961
hi
65962
hi
65963
hi
65964
hi
65965
hi
65966
hi
65967
hi
65968
hi
65969
hi
65970
hi
65971
hi
65972
hi
65973
hi
65974
hi
65975
hi
65976
hi
65977
hi
65978
hi
65979
hi
65980
hi
65981
hi
65982
hi
65983
hi
65984
hi
65985
hi
65986
hi
65987
hi
65988
hi
65989
hi
65990
hi
65991
hi
65992
hi
65993
hi
65994
hi
65995
hi
65996
hi
65997
hi
65998
hi
65999
hi
66000
hi
66001
hi
66002
hi
66003
hi
66004
hi
66005
hi
66006
hi
66007
hi
66008
hi
66009
hi
66010
hi
66011
hi
66012
hi
66013
hi
66014
hi
66015
hi
66016
hi
66017
hi
66018
hi
66019
hi
66020
hi
66021
hi
66022
hi
66023
hi
66024
hi
66025
hi
66026
hi
66027
hi
66028
hi
66029
hi
66030
hi
66031
hi
66032
hi
66033
hi
66034
hi
66035
hi
66036
hi
66037
hi
66038
hi
66039
hi
66040
hi
66041
hi
66042
hi
66043
hi
66044
hi
66045
hi
66046
hi
66047
hi
66048
hi
66049
hi
66050
hi
66051
hi
66052
hi
66053
hi
66054
hi
66055
hi
66056
hi
66057
hi
66058
hi
66059
hi
66060
hi
66061
hi
66062
hi
66063
hi
66064
hi
66065
hi
66066
hi
66067
hi
66068
hi
66069
hi
6

hi
67053
hi
67054
hi
67055
hi
67056
hi
67057
hi
67058
hi
67059
hi
67060
hi
67061
hi
67062
hi
67063
hi
67064
hi
67065
hi
67066
hi
67067
hi
67068
hi
67069
hi
67070
hi
67071
hi
67072
hi
67073
hi
67074
hi
67075
hi
67076
hi
67077
hi
67078
hi
67079
hi
67080
hi
67081
hi
67082
hi
67083
hi
67084
hi
67085
hi
67086
hi
67087
hi
67088
hi
67089
hi
67090
hi
67091
hi
67092
hi
67093
hi
67094
hi
67095
hi
67096
hi
67097
hi
67098
hi
67099
hi
67100
hi
67101
hi
67102
hi
67103
hi
67104
hi
67105
hi
67106
hi
67107
hi
67108
hi
67109
hi
67110
67111
hi
67112
67113
hi
67114
hi
67115
hi
67116
hi
67117
hi
67118
hi
67119
hi
67120
hi
67121
hi
67122
hi
67123
hi
67124
hi
67125
hi
67126
hi
67127
hi
67128
hi
67129
hi
67130
hi
67131
hi
67132
hi
67133
hi
67134
hi
67135
hi
67136
hi
67137
hi
67138
hi
67139
hi
67140
hi
67141
hi
67142
hi
67143
hi
67144
hi
67145
hi
67146
hi
67147
hi
67148
hi
67149
hi
67150
hi
67151
hi
67152
hi
67153
hi
67154
hi
67155
hi
67156
hi
67157
hi
67158
hi
67159
hi
67160
hi
67161
hi
67162
hi
67163
hi
6716

hi
68144
hi
68145
hi
68146
hi
68147
hi
68148
hi
68149
hi
68150
hi
68151
hi
68152
hi
68153
hi
68154
hi
68155
hi
68156
hi
68157
hi
68158
hi
68159
hi
68160
hi
68161
hi
68162
hi
68163
hi
68164
hi
68165
hi
68166
hi
68167
hi
68168
hi
68169
hi
68170
hi
68171
hi
68172
hi
68173
hi
68174
hi
68175
hi
68176
hi
68177
hi
68178
hi
68179
hi
68180
hi
68181
hi
68182
hi
68183
hi
68184
hi
68185
hi
68186
hi
68187
hi
68188
hi
68189
hi
68190
hi
68191
hi
68192
hi
68193
hi
68194
hi
68195
hi
68196
hi
68197
hi
68198
hi
68199
hi
68200
hi
68201
hi
68202
hi
68203
hi
68204
hi
68205
hi
68206
hi
68207
hi
68208
hi
68209
hi
68210
hi
68211
hi
68212
hi
68213
hi
68214
hi
68215
hi
68216
hi
68217
hi
68218
hi
68219
hi
68220
hi
68221
hi
68222
hi
68223
hi
68224
hi
68225
hi
68226
hi
68227
hi
68228
hi
68229
hi
68230
hi
68231
hi
68232
hi
68233
hi
68234
hi
68235
hi
68236
hi
68237
hi
68238
hi
68239
hi
68240
hi
68241
hi
68242
hi
68243
hi
68244
hi
68245
hi
68246
hi
68247
hi
68248
hi
68249
hi
68250
hi
68251
hi
68252
hi
68253
hi
68254
h

69243
hi
69244
hi
69245
hi
69246
hi
69247
hi
69248
hi
69249
hi
69250
hi
69251
hi
69252
hi
69253
hi
69254
hi
69255
hi
69256
hi
69257
hi
69258
hi
69259
hi
69260
hi
69261
hi
69262
hi
69263
hi
69264
hi
69265
hi
69266
hi
69267
hi
69268
hi
69269
69270
hi
69271
hi
69272
hi
69273
hi
69274
hi
69275
hi
69276
hi
69277
hi
69278
hi
69279
hi
69280
hi
69281
hi
69282
69283
hi
69284
hi
69285
69286
69287
69288
hi
69289
hi
69290
hi
69291
hi
69292
hi
69293
hi
69294
hi
69295
hi
69296
hi
69297
hi
69298
hi
69299
69300
69301
hi
69302
hi
69303
hi
69304
hi
69305
hi
69306
hi
69307
69308
69309
hi
69310
hi
69311
hi
69312
69313
69314
hi
69315
hi
69316
69317
hi
69318
hi
69319
hi
69320
hi
69321
hi
69322
hi
69323
hi
69324
hi
69325
hi
69326
hi
69327
69328
hi
69329
hi
69330
69331
hi
69332
hi
69333
hi
69334
hi
69335
hi
69336
hi
69337
hi
69338
69339
hi
69340
hi
69341
69342
hi
69343
hi
69344
69345
hi
69346
hi
69347
hi
69348
hi
69349
hi
69350
hi
69351
hi
69352
hi
69353
hi
69354
hi
69355
hi
69356
hi
69357
hi
69358
hi
69359
h

70395
hi
70396
hi
70397
hi
70398
hi
70399
hi
70400
hi
70401
hi
70402
hi
70403
70404
hi
70405
hi
70406
hi
70407
hi
70408
hi
70409
hi
70410
hi
70411
hi
70412
hi
70413
hi
70414
hi
70415
hi
70416
hi
70417
hi
70418
hi
70419
hi
70420
hi
70421
hi
70422
hi
70423
hi
70424
hi
70425
hi
70426
hi
70427
hi
70428
hi
70429
hi
70430
hi
70431
hi
70432
hi
70433
70434
70435
hi
70436
hi
70437
hi
70438
hi
70439
hi
70440
hi
70441
hi
70442
hi
70443
hi
70444
70445
hi
70446
hi
70447
hi
70448
hi
70449
hi
70450
hi
70451
hi
70452
hi
70453
hi
70454
hi
70455
hi
70456
hi
70457
hi
70458
hi
70459
hi
70460
hi
70461
hi
70462
hi
70463
hi
70464
hi
70465
hi
70466
hi
70467
hi
70468
hi
70469
hi
70470
hi
70471
hi
70472
hi
70473
hi
70474
hi
70475
70476
70477
hi
70478
hi
70479
hi
70480
hi
70481
hi
70482
hi
70483
hi
70484
hi
70485
70486
hi
70487
hi
70488
70489
70490
hi
70491
hi
70492
hi
70493
hi
70494
hi
70495
hi
70496
hi
70497
hi
70498
hi
70499
hi
70500
hi
70501
hi
70502
hi
70503
hi
70504
hi
70505
hi
70506
hi
70507
hi
70508
hi
7

hi
71545
hi
71546
hi
71547
hi
71548
hi
71549
hi
71550
hi
71551
hi
71552
hi
71553
hi
71554
hi
71555
hi
71556
hi
71557
hi
71558
hi
71559
hi
71560
hi
71561
hi
71562
hi
71563
hi
71564
hi
71565
hi
71566
hi
71567
hi
71568
hi
71569
hi
71570
hi
71571
hi
71572
hi
71573
hi
71574
hi
71575
hi
71576
hi
71577
hi
71578
hi
71579
hi
71580
hi
71581
hi
71582
hi
71583
hi
71584
hi
71585
hi
71586
hi
71587
hi
71588
hi
71589
hi
71590
hi
71591
hi
71592
hi
71593
hi
71594
hi
71595
71596
71597
hi
71598
hi
71599
hi
71600
hi
71601
hi
71602
hi
71603
hi
71604
hi
71605
hi
71606
hi
71607
hi
71608
hi
71609
hi
71610
71611
hi
71612
hi
71613
hi
71614
hi
71615
hi
71616
hi
71617
hi
71618
hi
71619
hi
71620
hi
71621
hi
71622
hi
71623
hi
71624
hi
71625
hi
71626
hi
71627
hi
71628
hi
71629
hi
71630
hi
71631
hi
71632
hi
71633
71634
71635
hi
71636
hi
71637
hi
71638
hi
71639
hi
71640
71641
hi
71642
hi
71643
hi
71644
hi
71645
hi
71646
hi
71647
hi
71648
hi
71649
hi
71650
hi
71651
71652
71653
hi
71654
hi
71655
hi
71656
hi
71657
hi
7165

72639
hi
72640
hi
72641
hi
72642
hi
72643
hi
72644
hi
72645
hi
72646
hi
72647
hi
72648
hi
72649
hi
72650
hi
72651
hi
72652
hi
72653
hi
72654
hi
72655
hi
72656
72657
hi
72658
hi
72659
hi
72660
72661
hi
72662
hi
72663
72664
hi
72665
hi
72666
hi
72667
hi
72668
hi
72669
hi
72670
hi
72671
hi
72672
hi
72673
hi
72674
hi
72675
hi
72676
hi
72677
hi
72678
hi
72679
hi
72680
hi
72681
hi
72682
hi
72683
hi
72684
hi
72685
hi
72686
hi
72687
hi
72688
hi
72689
hi
72690
hi
72691
hi
72692
hi
72693
hi
72694
hi
72695
hi
72696
hi
72697
hi
72698
hi
72699
hi
72700
hi
72701
hi
72702
hi
72703
hi
72704
hi
72705
hi
72706
hi
72707
hi
72708
hi
72709
hi
72710
hi
72711
hi
72712
hi
72713
hi
72714
hi
72715
hi
72716
72717
hi
72718
72719
72720
hi
72721
hi
72722
hi
72723
72724
hi
72725
hi
72726
hi
72727
hi
72728
72729
hi
72730
hi
72731
hi
72732
hi
72733
hi
72734
72735
72736
72737
hi
72738
hi
72739
hi
72740
hi
72741
hi
72742
hi
72743
72744
72745
hi
72746
hi
72747
72748
hi
72749
hi
72750
72751
hi
72752
72753
hi
72754
hi
7275

hi
73781
hi
73782
hi
73783
hi
73784
hi
73785
hi
73786
hi
73787
hi
73788
hi
73789
hi
73790
hi
73791
hi
73792
hi
73793
hi
73794
hi
73795
hi
73796
hi
73797
hi
73798
hi
73799
hi
73800
hi
73801
73802
hi
73803
hi
73804
hi
73805
hi
73806
hi
73807
hi
73808
hi
73809
hi
73810
hi
73811
hi
73812
hi
73813
hi
73814
hi
73815
hi
73816
hi
73817
hi
73818
73819
hi
73820
hi
73821
hi
73822
hi
73823
hi
73824
hi
73825
hi
73826
hi
73827
hi
73828
hi
73829
hi
73830
hi
73831
hi
73832
hi
73833
hi
73834
hi
73835
hi
73836
hi
73837
hi
73838
hi
73839
hi
73840
hi
73841
hi
73842
hi
73843
hi
73844
hi
73845
hi
73846
hi
73847
hi
73848
73849
hi
73850
hi
73851
hi
73852
hi
73853
hi
73854
hi
73855
hi
73856
hi
73857
hi
73858
hi
73859
hi
73860
73861
hi
73862
hi
73863
hi
73864
hi
73865
hi
73866
hi
73867
hi
73868
hi
73869
hi
73870
hi
73871
hi
73872
hi
73873
hi
73874
hi
73875
hi
73876
hi
73877
hi
73878
hi
73879
hi
73880
hi
73881
73882
hi
73883
hi
73884
hi
73885
73886
73887
hi
73888
hi
73889
hi
73890
hi
73891
hi
73892
hi
73893
hi
7

74918
hi
74919
hi
74920
hi
74921
hi
74922
hi
74923
hi
74924
hi
74925
hi
74926
hi
74927
hi
74928
74929
74930
74931
74932
hi
74933
hi
74934
hi
74935
hi
74936
hi
74937
hi
74938
hi
74939
hi
74940
hi
74941
hi
74942
hi
74943
hi
74944
hi
74945
hi
74946
hi
74947
hi
74948
74949
hi
74950
hi
74951
hi
74952
hi
74953
hi
74954
hi
74955
hi
74956
hi
74957
hi
74958
hi
74959
hi
74960
hi
74961
hi
74962
hi
74963
hi
74964
hi
74965
hi
74966
hi
74967
hi
74968
hi
74969
hi
74970
hi
74971
hi
74972
hi
74973
74974
74975
hi
74976
hi
74977
hi
74978
hi
74979
hi
74980
hi
74981
hi
74982
hi
74983
hi
74984
hi
74985
hi
74986
hi
74987
hi
74988
hi
74989
hi
74990
hi
74991
hi
74992
74993
hi
74994
hi
74995
hi
74996
hi
74997
hi
74998
hi
74999
hi
75000
hi
75001
hi
75002
hi
75003
hi
75004
75005
hi
75006
hi
75007
hi
75008
hi
75009
hi
75010
hi
75011
hi
75012
hi
75013
hi
75014
hi
75015
hi
75016
hi
75017
75018
hi
75019
hi
75020
hi
75021
hi
75022
hi
75023
hi
75024
hi
75025
hi
75026
hi
75027
hi
75028
hi
75029
hi
75030
hi
75031
hi
7503

76008
hi
76009
hi
76010
hi
76011
hi
76012
hi
76013
hi
76014
hi
76015
hi
76016
hi
76017
hi
76018
hi
76019
hi
76020
hi
76021
hi
76022
hi
76023
hi
76024
hi
76025
hi
76026
hi
76027
hi
76028
hi
76029
hi
76030
hi
76031
hi
76032
hi
76033
76034
hi
76035
hi
76036
hi
76037
76038
76039
hi
76040
hi
76041
hi
76042
hi
76043
hi
76044
hi
76045
hi
76046
hi
76047
hi
76048
hi
76049
hi
76050
hi
76051
hi
76052
hi
76053
hi
76054
hi
76055
hi
76056
hi
76057
hi
76058
hi
76059
hi
76060
hi
76061
hi
76062
hi
76063
hi
76064
hi
76065
hi
76066
hi
76067
hi
76068
hi
76069
hi
76070
hi
76071
hi
76072
hi
76073
hi
76074
hi
76075
hi
76076
hi
76077
hi
76078
hi
76079
hi
76080
hi
76081
hi
76082
hi
76083
hi
76084
hi
76085
hi
76086
hi
76087
hi
76088
hi
76089
hi
76090
hi
76091
hi
76092
hi
76093
hi
76094
hi
76095
hi
76096
76097
76098
hi
76099
hi
76100
hi
76101
76102
hi
76103
76104
hi
76105
hi
76106
hi
76107
hi
76108
hi
76109
hi
76110
hi
76111
hi
76112
hi
76113
hi
76114
hi
76115
hi
76116
hi
76117
hi
76118
hi
76119
hi
76120
hi
7612

hi
77155
hi
77156
hi
77157
hi
77158
hi
77159
hi
77160
hi
77161
hi
77162
hi
77163
hi
77164
hi
77165
hi
77166
hi
77167
hi
77168
hi
77169
hi
77170
hi
77171
hi
77172
hi
77173
hi
77174
hi
77175
hi
77176
hi
77177
hi
77178
hi
77179
hi
77180
hi
77181
hi
77182
hi
77183
hi
77184
hi
77185
hi
77186
hi
77187
hi
77188
hi
77189
hi
77190
hi
77191
hi
77192
hi
77193
hi
77194
hi
77195
hi
77196
hi
77197
hi
77198
hi
77199
hi
77200
hi
77201
hi
77202
hi
77203
hi
77204
hi
77205
hi
77206
hi
77207
hi
77208
hi
77209
hi
77210
hi
77211
hi
77212
hi
77213
hi
77214
hi
77215
hi
77216
hi
77217
hi
77218
hi
77219
hi
77220
hi
77221
hi
77222
77223
77224
77225
hi
77226
hi
77227
hi
77228
hi
77229
77230
hi
77231
hi
77232
hi
77233
hi
77234
hi
77235
hi
77236
hi
77237
hi
77238
hi
77239
hi
77240
hi
77241
hi
77242
hi
77243
hi
77244
hi
77245
hi
77246
hi
77247
hi
77248
hi
77249
hi
77250
hi
77251
hi
77252
hi
77253
hi
77254
hi
77255
hi
77256
hi
77257
hi
77258
hi
77259
hi
77260
hi
77261
hi
77262
hi
77263
hi
77264
hi
77265
hi
77266
hi
7

hi
78273
hi
78274
hi
78275
hi
78276
hi
78277
hi
78278
hi
78279
hi
78280
hi
78281
hi
78282
hi
78283
hi
78284
hi
78285
hi
78286
hi
78287
hi
78288
hi
78289
hi
78290
hi
78291
hi
78292
hi
78293
hi
78294
hi
78295
78296
78297
hi
78298
hi
78299
hi
78300
78301
hi
78302
hi
78303
hi
78304
hi
78305
hi
78306
hi
78307
hi
78308
hi
78309
hi
78310
hi
78311
hi
78312
hi
78313
hi
78314
hi
78315
hi
78316
hi
78317
hi
78318
hi
78319
hi
78320
hi
78321
hi
78322
hi
78323
hi
78324
hi
78325
hi
78326
hi
78327
hi
78328
hi
78329
hi
78330
hi
78331
hi
78332
hi
78333
hi
78334
hi
78335
hi
78336
hi
78337
hi
78338
hi
78339
hi
78340
hi
78341
hi
78342
hi
78343
hi
78344
hi
78345
hi
78346
hi
78347
hi
78348
hi
78349
hi
78350
hi
78351
hi
78352
hi
78353
hi
78354
hi
78355
hi
78356
hi
78357
hi
78358
hi
78359
hi
78360
hi
78361
hi
78362
hi
78363
hi
78364
hi
78365
hi
78366
hi
78367
hi
78368
hi
78369
hi
78370
hi
78371
hi
78372
hi
78373
hi
78374
hi
78375
hi
78376
hi
78377
hi
78378
hi
78379
hi
78380
hi
78381
hi
78382
hi
78383
hi
78384
h

79394
hi
79395
hi
79396
hi
79397
hi
79398
hi
79399
hi
79400
hi
79401
hi
79402
hi
79403
hi
79404
hi
79405
hi
79406
hi
79407
hi
79408
hi
79409
hi
79410
hi
79411
hi
79412
hi
79413
hi
79414
hi
79415
hi
79416
hi
79417
hi
79418
79419
hi
79420
hi
79421
hi
79422
hi
79423
hi
79424
hi
79425
hi
79426
hi
79427
hi
79428
hi
79429
hi
79430
hi
79431
hi
79432
hi
79433
hi
79434
hi
79435
hi
79436
hi
79437
hi
79438
hi
79439
hi
79440
hi
79441
hi
79442
hi
79443
hi
79444
hi
79445
hi
79446
hi
79447
hi
79448
hi
79449
hi
79450
hi
79451
hi
79452
hi
79453
hi
79454
hi
79455
hi
79456
hi
79457
hi
79458
hi
79459
hi
79460
hi
79461
hi
79462
hi
79463
hi
79464
hi
79465
hi
79466
hi
79467
hi
79468
hi
79469
hi
79470
hi
79471
hi
79472
hi
79473
hi
79474
hi
79475
hi
79476
hi
79477
hi
79478
hi
79479
hi
79480
hi
79481
hi
79482
hi
79483
hi
79484
hi
79485
hi
79486
hi
79487
hi
79488
hi
79489
hi
79490
hi
79491
hi
79492
hi
79493
hi
79494
hi
79495
hi
79496
hi
79497
hi
79498
hi
79499
hi
79500
hi
79501
hi
79502
hi
79503
hi
79504
hi
7950

80487
hi
80488
hi
80489
hi
80490
hi
80491
hi
80492
hi
80493
hi
80494
hi
80495
hi
80496
hi
80497
hi
80498
hi
80499
hi
80500
hi
80501
hi
80502
hi
80503
hi
80504
hi
80505
hi
80506
hi
80507
hi
80508
hi
80509
hi
80510
hi
80511
hi
80512
hi
80513
hi
80514
hi
80515
hi
80516
hi
80517
hi
80518
hi
80519
hi
80520
hi
80521
hi
80522
hi
80523
hi
80524
hi
80525
hi
80526
hi
80527
hi
80528
hi
80529
hi
80530
hi
80531
hi
80532
hi
80533
hi
80534
hi
80535
hi
80536
hi
80537
hi
80538
hi
80539
hi
80540
hi
80541
hi
80542
hi
80543
hi
80544
hi
80545
hi
80546
hi
80547
hi
80548
hi
80549
hi
80550
hi
80551
hi
80552
hi
80553
hi
80554
hi
80555
hi
80556
hi
80557
hi
80558
hi
80559
hi
80560
hi
80561
hi
80562
hi
80563
hi
80564
hi
80565
hi
80566
hi
80567
hi
80568
hi
80569
hi
80570
hi
80571
hi
80572
hi
80573
hi
80574
hi
80575
hi
80576
hi
80577
hi
80578
hi
80579
hi
80580
hi
80581
hi
80582
hi
80583
hi
80584
hi
80585
hi
80586
hi
80587
hi
80588
hi
80589
hi
80590
hi
80591
hi
80592
hi
80593
hi
80594
hi
80595
hi
80596
hi
80597
hi
8

81567
hi
81568
hi
81569
hi
81570
hi
81571
hi
81572
hi
81573
hi
81574
hi
81575
hi
81576
hi
81577
hi
81578
hi
81579
hi
81580
hi
81581
hi
81582
hi
81583
hi
81584
hi
81585
hi
81586
hi
81587
hi
81588
hi
81589
hi
81590
hi
81591
hi
81592
hi
81593
hi
81594
hi
81595
hi
81596
hi
81597
hi
81598
hi
81599
hi
81600
hi
81601
hi
81602
hi
81603
hi
81604
hi
81605
hi
81606
hi
81607
hi
81608
hi
81609
hi
81610
hi
81611
hi
81612
hi
81613
hi
81614
hi
81615
hi
81616
hi
81617
hi
81618
hi
81619
hi
81620
hi
81621
hi
81622
hi
81623
hi
81624
hi
81625
hi
81626
hi
81627
hi
81628
hi
81629
hi
81630
hi
81631
hi
81632
hi
81633
hi
81634
hi
81635
hi
81636
hi
81637
hi
81638
hi
81639
hi
81640
hi
81641
hi
81642
hi
81643
hi
81644
hi
81645
hi
81646
hi
81647
hi
81648
hi
81649
hi
81650
hi
81651
hi
81652
hi
81653
hi
81654
hi
81655
hi
81656
hi
81657
hi
81658
hi
81659
hi
81660
hi
81661
hi
81662
hi
81663
hi
81664
hi
81665
hi
81666
hi
81667
hi
81668
hi
81669
hi
81670
hi
81671
hi
81672
hi
81673
hi
81674
hi
81675
hi
81676
hi
81677
hi
8

hi
82636
hi
82637
hi
82638
hi
82639
hi
82640
hi
82641
hi
82642
hi
82643
hi
82644
hi
82645
hi
82646
hi
82647
hi
82648
hi
82649
hi
82650
hi
82651
hi
82652
hi
82653
hi
82654
hi
82655
hi
82656
hi
82657
hi
82658
hi
82659
hi
82660
hi
82661
hi
82662
hi
82663
hi
82664
hi
82665
hi
82666
hi
82667
hi
82668
hi
82669
hi
82670
hi
82671
hi
82672
hi
82673
hi
82674
hi
82675
hi
82676
hi
82677
hi
82678
hi
82679
hi
82680
hi
82681
hi
82682
hi
82683
hi
82684
hi
82685
hi
82686
hi
82687
hi
82688
hi
82689
hi
82690
hi
82691
hi
82692
hi
82693
hi
82694
hi
82695
hi
82696
hi
82697
hi
82698
hi
82699
hi
82700
hi
82701
hi
82702
hi
82703
hi
82704
hi
82705
hi
82706
hi
82707
hi
82708
hi
82709
hi
82710
hi
82711
hi
82712
hi
82713
hi
82714
hi
82715
hi
82716
hi
82717
hi
82718
hi
82719
hi
82720
hi
82721
hi
82722
hi
82723
hi
82724
hi
82725
hi
82726
82727
hi
82728
hi
82729
82730
82731
hi
82732
82733
82734
82735
82736
hi
82737
hi
82738
hi
82739
hi
82740
hi
82741
hi
82742
82743
82744
82745
82746
hi
82747
hi
82748
hi
82749
hi
8275

83775
hi
83776
hi
83777
hi
83778
hi
83779
hi
83780
hi
83781
hi
83782
hi
83783
hi
83784
hi
83785
hi
83786
hi
83787
hi
83788
hi
83789
hi
83790
hi
83791
hi
83792
hi
83793
hi
83794
hi
83795
hi
83796
hi
83797
hi
83798
hi
83799
hi
83800
hi
83801
hi
83802
hi
83803
hi
83804
hi
83805
hi
83806
hi
83807
hi
83808
hi
83809
hi
83810
hi
83811
hi
83812
hi
83813
hi
83814
hi
83815
hi
83816
hi
83817
hi
83818
hi
83819
hi
83820
hi
83821
hi
83822
hi
83823
hi
83824
hi
83825
hi
83826
hi
83827
hi
83828
hi
83829
hi
83830
hi
83831
hi
83832
hi
83833
hi
83834
hi
83835
hi
83836
hi
83837
hi
83838
hi
83839
hi
83840
hi
83841
hi
83842
hi
83843
hi
83844
hi
83845
hi
83846
hi
83847
hi
83848
hi
83849
hi
83850
hi
83851
hi
83852
hi
83853
hi
83854
hi
83855
hi
83856
hi
83857
hi
83858
hi
83859
hi
83860
hi
83861
hi
83862
hi
83863
hi
83864
hi
83865
hi
83866
hi
83867
hi
83868
hi
83869
hi
83870
hi
83871
hi
83872
hi
83873
hi
83874
hi
83875
hi
83876
hi
83877
hi
83878
hi
83879
hi
83880
hi
83881
hi
83882
hi
83883
hi
83884
hi
83885
hi
8

84892
hi
84893
hi
84894
hi
84895
hi
84896
hi
84897
hi
84898
hi
84899
hi
84900
hi
84901
hi
84902
hi
84903
hi
84904
hi
84905
hi
84906
hi
84907
hi
84908
hi
84909
hi
84910
hi
84911
hi
84912
hi
84913
hi
84914
hi
84915
hi
84916
hi
84917
hi
84918
hi
84919
hi
84920
hi
84921
hi
84922
hi
84923
hi
84924
hi
84925
hi
84926
hi
84927
hi
84928
hi
84929
hi
84930
hi
84931
hi
84932
hi
84933
hi
84934
hi
84935
hi
84936
hi
84937
hi
84938
hi
84939
hi
84940
hi
84941
hi
84942
hi
84943
hi
84944
hi
84945
hi
84946
hi
84947
hi
84948
hi
84949
hi
84950
hi
84951
hi
84952
hi
84953
hi
84954
hi
84955
hi
84956
hi
84957
hi
84958
hi
84959
hi
84960
hi
84961
hi
84962
hi
84963
hi
84964
hi
84965
hi
84966
hi
84967
hi
84968
hi
84969
hi
84970
hi
84971
hi
84972
hi
84973
hi
84974
hi
84975
hi
84976
hi
84977
hi
84978
hi
84979
hi
84980
hi
84981
hi
84982
hi
84983
hi
84984
hi
84985
hi
84986
hi
84987
hi
84988
hi
84989
hi
84990
hi
84991
hi
84992
hi
84993
hi
84994
hi
84995
hi
84996
hi
84997
hi
84998
hi
84999
hi
85000
hi
85001
hi
85002
hi
8

hi
85991
hi
85992
hi
85993
hi
85994
hi
85995
hi
85996
hi
85997
hi
85998
hi
85999
hi
86000
hi
86001
hi
86002
hi
86003
hi
86004
hi
86005
hi
86006
hi
86007
hi
86008
hi
86009
hi
86010
hi
86011
hi
86012
hi
86013
hi
86014
hi
86015
hi
86016
hi
86017
hi
86018
hi
86019
hi
86020
hi
86021
hi
86022
hi
86023
hi
86024
hi
86025
hi
86026
hi
86027
hi
86028
hi
86029
hi
86030
hi
86031
hi
86032
hi
86033
hi
86034
hi
86035
hi
86036
86037
hi
86038
hi
86039
hi
86040
hi
86041
hi
86042
hi
86043
hi
86044
hi
86045
hi
86046
hi
86047
hi
86048
hi
86049
hi
86050
hi
86051
hi
86052
hi
86053
hi
86054
hi
86055
hi
86056
hi
86057
hi
86058
hi
86059
hi
86060
hi
86061
hi
86062
hi
86063
hi
86064
hi
86065
hi
86066
hi
86067
hi
86068
hi
86069
hi
86070
hi
86071
hi
86072
hi
86073
hi
86074
hi
86075
hi
86076
hi
86077
hi
86078
hi
86079
hi
86080
hi
86081
hi
86082
hi
86083
hi
86084
hi
86085
hi
86086
hi
86087
hi
86088
hi
86089
86090
hi
86091
hi
86092
hi
86093
hi
86094
hi
86095
hi
86096
hi
86097
hi
86098
hi
86099
hi
86100
hi
86101
hi
8610

87076
hi
87077
hi
87078
hi
87079
hi
87080
hi
87081
hi
87082
hi
87083
hi
87084
hi
87085
hi
87086
hi
87087
hi
87088
hi
87089
hi
87090
hi
87091
hi
87092
hi
87093
hi
87094
hi
87095
hi
87096
hi
87097
hi
87098
hi
87099
hi
87100
hi
87101
hi
87102
hi
87103
hi
87104
hi
87105
hi
87106
hi
87107
hi
87108
hi
87109
hi
87110
hi
87111
hi
87112
hi
87113
hi
87114
hi
87115
hi
87116
hi
87117
hi
87118
hi
87119
hi
87120
hi
87121
hi
87122
hi
87123
hi
87124
hi
87125
hi
87126
hi
87127
hi
87128
hi
87129
hi
87130
hi
87131
hi
87132
hi
87133
hi
87134
hi
87135
hi
87136
hi
87137
hi
87138
hi
87139
hi
87140
hi
87141
hi
87142
hi
87143
hi
87144
hi
87145
hi
87146
hi
87147
hi
87148
hi
87149
hi
87150
hi
87151
hi
87152
hi
87153
hi
87154
hi
87155
hi
87156
hi
87157
hi
87158
hi
87159
hi
87160
hi
87161
hi
87162
hi
87163
hi
87164
hi
87165
hi
87166
hi
87167
hi
87168
hi
87169
hi
87170
hi
87171
hi
87172
hi
87173
hi
87174
hi
87175
hi
87176
hi
87177
hi
87178
hi
87179
hi
87180
hi
87181
hi
87182
hi
87183
hi
87184
hi
87185
hi
87186
hi
8

hi
88153
hi
88154
hi
88155
hi
88156
hi
88157
hi
88158
hi
88159
hi
88160
hi
88161
hi
88162
hi
88163
hi
88164
hi
88165
hi
88166
hi
88167
hi
88168
hi
88169
hi
88170
hi
88171
hi
88172
hi
88173
hi
88174
hi
88175
hi
88176
hi
88177
hi
88178
hi
88179
hi
88180
hi
88181
hi
88182
hi
88183
hi
88184
hi
88185
hi
88186
hi
88187
hi
88188
hi
88189
hi
88190
hi
88191
hi
88192
hi
88193
hi
88194
hi
88195
hi
88196
hi
88197
hi
88198
hi
88199
hi
88200
hi
88201
hi
88202
hi
88203
hi
88204
hi
88205
hi
88206
hi
88207
hi
88208
hi
88209
hi
88210
hi
88211
hi
88212
hi
88213
hi
88214
hi
88215
hi
88216
hi
88217
hi
88218
hi
88219
hi
88220
hi
88221
hi
88222
hi
88223
hi
88224
hi
88225
88226
hi
88227
hi
88228
hi
88229
hi
88230
hi
88231
hi
88232
hi
88233
hi
88234
hi
88235
hi
88236
hi
88237
hi
88238
hi
88239
hi
88240
hi
88241
hi
88242
hi
88243
hi
88244
hi
88245
hi
88246
hi
88247
hi
88248
hi
88249
hi
88250
hi
88251
hi
88252
hi
88253
hi
88254
hi
88255
hi
88256
hi
88257
hi
88258
hi
88259
hi
88260
hi
88261
hi
88262
hi
88263
hi
8

hi
89238
hi
89239
hi
89240
hi
89241
hi
89242
hi
89243
hi
89244
hi
89245
hi
89246
hi
89247
hi
89248
hi
89249
hi
89250
hi
89251
hi
89252
hi
89253
hi
89254
hi
89255
hi
89256
hi
89257
hi
89258
hi
89259
hi
89260
hi
89261
hi
89262
89263
hi
89264
hi
89265
hi
89266
hi
89267
hi
89268
hi
89269
hi
89270
hi
89271
hi
89272
hi
89273
hi
89274
hi
89275
hi
89276
hi
89277
hi
89278
hi
89279
hi
89280
hi
89281
hi
89282
hi
89283
hi
89284
hi
89285
hi
89286
hi
89287
hi
89288
hi
89289
hi
89290
hi
89291
hi
89292
hi
89293
hi
89294
hi
89295
hi
89296
hi
89297
hi
89298
hi
89299
hi
89300
hi
89301
hi
89302
hi
89303
hi
89304
hi
89305
hi
89306
hi
89307
hi
89308
hi
89309
hi
89310
hi
89311
hi
89312
hi
89313
hi
89314
hi
89315
hi
89316
hi
89317
hi
89318
hi
89319
hi
89320
hi
89321
hi
89322
hi
89323
hi
89324
hi
89325
hi
89326
hi
89327
hi
89328
hi
89329
hi
89330
hi
89331
hi
89332
hi
89333
hi
89334
hi
89335
hi
89336
hi
89337
hi
89338
hi
89339
hi
89340
hi
89341
89342
hi
89343
hi
89344
hi
89345
hi
89346
hi
89347
hi
89348
hi
8934

90335
hi
90336
hi
90337
hi
90338
hi
90339
hi
90340
hi
90341
hi
90342
hi
90343
hi
90344
hi
90345
hi
90346
hi
90347
hi
90348
hi
90349
hi
90350
hi
90351
hi
90352
hi
90353
hi
90354
hi
90355
hi
90356
hi
90357
hi
90358
hi
90359
hi
90360
hi
90361
hi
90362
hi
90363
hi
90364
hi
90365
hi
90366
hi
90367
hi
90368
hi
90369
hi
90370
hi
90371
hi
90372
hi
90373
90374
hi
90375
hi
90376
hi
90377
hi
90378
hi
90379
hi
90380
hi
90381
hi
90382
hi
90383
hi
90384
hi
90385
hi
90386
hi
90387
hi
90388
hi
90389
hi
90390
hi
90391
hi
90392
hi
90393
hi
90394
hi
90395
hi
90396
hi
90397
hi
90398
hi
90399
hi
90400
hi
90401
hi
90402
hi
90403
hi
90404
hi
90405
hi
90406
hi
90407
hi
90408
hi
90409
hi
90410
hi
90411
hi
90412
hi
90413
hi
90414
hi
90415
hi
90416
hi
90417
hi
90418
hi
90419
hi
90420
hi
90421
hi
90422
hi
90423
hi
90424
hi
90425
hi
90426
hi
90427
hi
90428
hi
90429
hi
90430
hi
90431
hi
90432
hi
90433
hi
90434
hi
90435
hi
90436
hi
90437
hi
90438
hi
90439
hi
90440
hi
90441
hi
90442
hi
90443
hi
90444
hi
90445
hi
9044

hi
91469
hi
91470
hi
91471
hi
91472
hi
91473
hi
91474
hi
91475
hi
91476
hi
91477
hi
91478
hi
91479
hi
91480
hi
91481
hi
91482
hi
91483
hi
91484
hi
91485
hi
91486
hi
91487
hi
91488
91489
hi
91490
hi
91491
hi
91492
hi
91493
hi
91494
hi
91495
hi
91496
hi
91497
hi
91498
hi
91499
hi
91500
hi
91501
hi
91502
hi
91503
hi
91504
hi
91505
hi
91506
hi
91507
hi
91508
hi
91509
hi
91510
hi
91511
hi
91512
hi
91513
hi
91514
hi
91515
hi
91516
hi
91517
hi
91518
hi
91519
91520
91521
hi
91522
hi
91523
hi
91524
hi
91525
hi
91526
hi
91527
hi
91528
hi
91529
hi
91530
hi
91531
hi
91532
hi
91533
hi
91534
hi
91535
hi
91536
hi
91537
hi
91538
hi
91539
hi
91540
hi
91541
hi
91542
hi
91543
hi
91544
hi
91545
hi
91546
hi
91547
hi
91548
hi
91549
hi
91550
hi
91551
hi
91552
hi
91553
hi
91554
hi
91555
hi
91556
hi
91557
hi
91558
hi
91559
hi
91560
hi
91561
hi
91562
hi
91563
hi
91564
hi
91565
hi
91566
hi
91567
hi
91568
hi
91569
hi
91570
hi
91571
hi
91572
hi
91573
hi
91574
hi
91575
hi
91576
hi
91577
hi
91578
hi
91579
hi
91580
h

hi
92616
hi
92617
92618
92619
92620
92621
hi
92622
hi
92623
hi
92624
hi
92625
hi
92626
hi
92627
hi
92628
hi
92629
hi
92630
hi
92631
hi
92632
hi
92633
hi
92634
hi
92635
hi
92636
hi
92637
hi
92638
hi
92639
hi
92640
hi
92641
hi
92642
hi
92643
hi
92644
hi
92645
hi
92646
hi
92647
hi
92648
hi
92649
hi
92650
hi
92651
hi
92652
hi
92653
hi
92654
hi
92655
hi
92656
hi
92657
hi
92658
hi
92659
hi
92660
hi
92661
hi
92662
hi
92663
hi
92664
hi
92665
hi
92666
hi
92667
hi
92668
hi
92669
hi
92670
hi
92671
hi
92672
hi
92673
hi
92674
hi
92675
hi
92676
hi
92677
hi
92678
hi
92679
hi
92680
hi
92681
hi
92682
hi
92683
hi
92684
hi
92685
hi
92686
hi
92687
hi
92688
hi
92689
hi
92690
hi
92691
hi
92692
hi
92693
hi
92694
hi
92695
hi
92696
hi
92697
hi
92698
hi
92699
hi
92700
hi
92701
hi
92702
hi
92703
hi
92704
hi
92705
hi
92706
hi
92707
hi
92708
hi
92709
hi
92710
hi
92711
hi
92712
hi
92713
hi
92714
hi
92715
hi
92716
hi
92717
hi
92718
hi
92719
hi
92720
hi
92721
hi
92722
hi
92723
hi
92724
hi
92725
hi
92726
hi
92727
hi
9

hi
93701
hi
93702
hi
93703
hi
93704
hi
93705
hi
93706
hi
93707
hi
93708
hi
93709
hi
93710
hi
93711
hi
93712
hi
93713
hi
93714
hi
93715
hi
93716
hi
93717
hi
93718
hi
93719
hi
93720
hi
93721
hi
93722
hi
93723
hi
93724
hi
93725
hi
93726
hi
93727
hi
93728
hi
93729
hi
93730
hi
93731
hi
93732
hi
93733
hi
93734
hi
93735
hi
93736
hi
93737
hi
93738
hi
93739
hi
93740
hi
93741
hi
93742
hi
93743
hi
93744
hi
93745
hi
93746
hi
93747
hi
93748
hi
93749
hi
93750
hi
93751
hi
93752
hi
93753
hi
93754
hi
93755
hi
93756
hi
93757
hi
93758
hi
93759
hi
93760
hi
93761
hi
93762
hi
93763
hi
93764
hi
93765
hi
93766
hi
93767
hi
93768
hi
93769
hi
93770
hi
93771
hi
93772
hi
93773
hi
93774
hi
93775
hi
93776
hi
93777
hi
93778
hi
93779
hi
93780
hi
93781
hi
93782
hi
93783
93784
93785
hi
93786
hi
93787
hi
93788
hi
93789
hi
93790
hi
93791
hi
93792
hi
93793
hi
93794
hi
93795
hi
93796
hi
93797
hi
93798
hi
93799
hi
93800
hi
93801
hi
93802
hi
93803
hi
93804
hi
93805
hi
93806
hi
93807
hi
93808
hi
93809
hi
93810
hi
93811
hi
9381

94789
hi
94790
hi
94791
hi
94792
hi
94793
hi
94794
hi
94795
hi
94796
hi
94797
hi
94798
hi
94799
hi
94800
hi
94801
hi
94802
hi
94803
hi
94804
hi
94805
hi
94806
hi
94807
hi
94808
hi
94809
hi
94810
hi
94811
hi
94812
hi
94813
hi
94814
hi
94815
hi
94816
hi
94817
hi
94818
hi
94819
hi
94820
hi
94821
hi
94822
hi
94823
hi
94824
hi
94825
hi
94826
hi
94827
hi
94828
hi
94829
hi
94830
hi
94831
hi
94832
hi
94833
hi
94834
hi
94835
hi
94836
hi
94837
hi
94838
hi
94839
hi
94840
hi
94841
hi
94842
hi
94843
hi
94844
hi
94845
hi
94846
hi
94847
hi
94848
hi
94849
hi
94850
hi
94851
hi
94852
hi
94853
hi
94854
hi
94855
hi
94856
hi
94857
hi
94858
hi
94859
hi
94860
hi
94861
hi
94862
hi
94863
hi
94864
hi
94865
hi
94866
hi
94867
hi
94868
hi
94869
hi
94870
hi
94871
hi
94872
hi
94873
hi
94874
hi
94875
hi
94876
hi
94877
hi
94878
hi
94879
hi
94880
hi
94881
94882
hi
94883
hi
94884
hi
94885
hi
94886
hi
94887
hi
94888
hi
94889
hi
94890
hi
94891
hi
94892
hi
94893
hi
94894
hi
94895
hi
94896
hi
94897
hi
94898
hi
94899
hi
9490

hi
95908
hi
95909
hi
95910
hi
95911
hi
95912
hi
95913
hi
95914
hi
95915
hi
95916
hi
95917
hi
95918
hi
95919
hi
95920
hi
95921
hi
95922
hi
95923
hi
95924
hi
95925
hi
95926
hi
95927
hi
95928
hi
95929
hi
95930
hi
95931
hi
95932
hi
95933
hi
95934
hi
95935
hi
95936
hi
95937
hi
95938
hi
95939
hi
95940
hi
95941
hi
95942
hi
95943
hi
95944
hi
95945
hi
95946
hi
95947
hi
95948
hi
95949
hi
95950
hi
95951
hi
95952
hi
95953
hi
95954
hi
95955
hi
95956
hi
95957
hi
95958
hi
95959
hi
95960
hi
95961
hi
95962
hi
95963
hi
95964
hi
95965
hi
95966
hi
95967
hi
95968
hi
95969
hi
95970
hi
95971
hi
95972
hi
95973
hi
95974
hi
95975
hi
95976
hi
95977
hi
95978
hi
95979
hi
95980
hi
95981
hi
95982
hi
95983
hi
95984
hi
95985
hi
95986
hi
95987
hi
95988
hi
95989
hi
95990
hi
95991
hi
95992
hi
95993
hi
95994
hi
95995
hi
95996
hi
95997
hi
95998
hi
95999
hi
96000
hi
96001
hi
96002
hi
96003
hi
96004
hi
96005
hi
96006
hi
96007
hi
96008
hi
96009
hi
96010
hi
96011
hi
96012
hi
96013
hi
96014
hi
96015
hi
96016
hi
96017
hi
96018
h

hi
97011
hi
97012
hi
97013
hi
97014
hi
97015
hi
97016
hi
97017
hi
97018
hi
97019
hi
97020
hi
97021
hi
97022
hi
97023
hi
97024
hi
97025
hi
97026
hi
97027
hi
97028
hi
97029
hi
97030
hi
97031
hi
97032
hi
97033
hi
97034
hi
97035
hi
97036
hi
97037
hi
97038
hi
97039
hi
97040
hi
97041
hi
97042
hi
97043
hi
97044
hi
97045
hi
97046
hi
97047
hi
97048
hi
97049
hi
97050
hi
97051
hi
97052
hi
97053
hi
97054
hi
97055
hi
97056
hi
97057
hi
97058
hi
97059
hi
97060
hi
97061
hi
97062
hi
97063
hi
97064
hi
97065
hi
97066
hi
97067
hi
97068
hi
97069
hi
97070
hi
97071
hi
97072
hi
97073
hi
97074
hi
97075
hi
97076
hi
97077
hi
97078
hi
97079
hi
97080
hi
97081
hi
97082
hi
97083
hi
97084
hi
97085
hi
97086
hi
97087
hi
97088
hi
97089
hi
97090
hi
97091
hi
97092
hi
97093
hi
97094
hi
97095
hi
97096
hi
97097
hi
97098
hi
97099
hi
97100
hi
97101
hi
97102
hi
97103
hi
97104
hi
97105
hi
97106
hi
97107
hi
97108
hi
97109
hi
97110
hi
97111
hi
97112
hi
97113
hi
97114
hi
97115
hi
97116
hi
97117
hi
97118
hi
97119
hi
97120
hi
97121
h

98114
hi
98115
hi
98116
hi
98117
hi
98118
hi
98119
hi
98120
hi
98121
hi
98122
hi
98123
hi
98124
hi
98125
hi
98126
hi
98127
hi
98128
hi
98129
hi
98130
hi
98131
hi
98132
hi
98133
hi
98134
hi
98135
hi
98136
hi
98137
hi
98138
hi
98139
hi
98140
hi
98141
hi
98142
hi
98143
hi
98144
hi
98145
hi
98146
hi
98147
hi
98148
hi
98149
hi
98150
hi
98151
hi
98152
hi
98153
hi
98154
hi
98155
hi
98156
hi
98157
hi
98158
hi
98159
hi
98160
hi
98161
hi
98162
hi
98163
hi
98164
hi
98165
hi
98166
hi
98167
hi
98168
hi
98169
hi
98170
hi
98171
hi
98172
hi
98173
hi
98174
hi
98175
hi
98176
hi
98177
hi
98178
hi
98179
hi
98180
hi
98181
hi
98182
hi
98183
hi
98184
hi
98185
hi
98186
hi
98187
hi
98188
hi
98189
hi
98190
hi
98191
hi
98192
hi
98193
hi
98194
hi
98195
hi
98196
hi
98197
hi
98198
hi
98199
hi
98200
hi
98201
hi
98202
hi
98203
hi
98204
hi
98205
hi
98206
hi
98207
hi
98208
hi
98209
hi
98210
hi
98211
hi
98212
hi
98213
hi
98214
hi
98215
hi
98216
hi
98217
hi
98218
hi
98219
hi
98220
hi
98221
hi
98222
hi
98223
hi
98224
hi
9

99210
hi
99211
hi
99212
hi
99213
hi
99214
hi
99215
hi
99216
hi
99217
hi
99218
hi
99219
hi
99220
hi
99221
hi
99222
hi
99223
hi
99224
hi
99225
hi
99226
hi
99227
hi
99228
hi
99229
hi
99230
hi
99231
hi
99232
hi
99233
hi
99234
hi
99235
hi
99236
hi
99237
hi
99238
hi
99239
hi
99240
hi
99241
hi
99242
hi
99243
hi
99244
hi
99245
hi
99246
hi
99247
hi
99248
hi
99249
hi
99250
hi
99251
hi
99252
hi
99253
hi
99254
hi
99255
hi
99256
hi
99257
hi
99258
hi
99259
hi
99260
hi
99261
hi
99262
hi
99263
hi
99264
hi
99265
hi
99266
hi
99267
hi
99268
hi
99269
hi
99270
hi
99271
hi
99272
hi
99273
hi
99274
hi
99275
hi
99276
hi
99277
hi
99278
hi
99279
hi
99280
hi
99281
hi
99282
hi
99283
hi
99284
hi
99285
hi
99286
hi
99287
hi
99288
hi
99289
hi
99290
hi
99291
hi
99292
hi
99293
hi
99294
hi
99295
hi
99296
hi
99297
hi
99298
hi
99299
hi
99300
hi
99301
hi
99302
hi
99303
hi
99304
hi
99305
hi
99306
hi
99307
hi
99308
hi
99309
hi
99310
hi
99311
hi
99312
hi
99313
hi
99314
hi
99315
hi
99316
hi
99317
hi
99318
hi
99319
hi
99320
hi
9

100295
hi
100296
hi
100297
hi
100298
hi
100299
hi
100300
hi
100301
hi
100302
hi
100303
hi
100304
hi
100305
hi
100306
hi
100307
hi
100308
hi
100309
hi
100310
hi
100311
hi
100312
hi
100313
hi
100314
hi
100315
hi
100316
hi
100317
hi
100318
hi
100319
hi
100320
hi
100321
hi
100322
hi
100323
hi
100324
hi
100325
hi
100326
hi
100327
hi
100328
hi
100329
hi
100330
hi
100331
hi
100332
hi
100333
hi
100334
hi
100335
hi
100336
hi
100337
hi
100338
hi
100339
hi
100340
hi
100341
hi
100342
hi
100343
hi
100344
hi
100345
hi
100346
hi
100347
hi
100348
hi
100349
hi
100350
hi
100351
hi
100352
hi
100353
hi
100354
hi
100355
hi
100356
hi
100357
hi
100358
hi
100359
hi
100360
hi
100361
hi
100362
hi
100363
hi
100364
hi
100365
hi
100366
hi
100367
hi
100368
hi
100369
hi
100370
hi
100371
hi
100372
hi
100373
hi
100374
hi
100375
hi
100376
hi
100377
hi
100378
hi
100379
hi
100380
hi
100381
hi
100382
hi
100383
hi
100384
hi
100385
hi
100386
hi
100387
hi
100388
hi
100389
hi
100390
hi
100391
hi
100392
hi
100393
hi
100394
hi


101158
hi
101159
hi
101160
hi
101161
hi
101162
hi
101163
hi
101164
hi
101165
hi
101166
hi
101167
hi
101168
hi
101169
hi
101170
hi
101171
hi
101172
hi
101173
hi
101174
hi
101175
hi
101176
hi
101177
hi
101178
hi
101179
hi
101180
hi
101181
hi
101182
hi
101183
hi
101184
hi
101185
hi
101186
hi
101187
hi
101188
hi
101189
hi
101190
hi
101191
hi
101192
hi
101193
hi
101194
hi
101195
hi
101196
hi
101197
hi
101198
hi
101199
hi
101200
hi
101201
hi
101202
hi
101203
hi
101204
hi
101205
hi
101206
hi
101207
hi
101208
hi
101209
hi
101210
hi
101211
hi
101212
hi
101213
hi
101214
hi
101215
hi
101216
hi
101217
hi
101218
hi
101219
hi
101220
hi
101221
hi
101222
hi
101223
hi
101224
hi
101225
hi
101226
hi
101227
hi
101228
hi
101229
hi
101230
hi
101231
hi
101232
hi
101233
hi
101234
hi
101235
hi
101236
hi
101237
hi
101238
hi
101239
hi
101240
hi
101241
hi
101242
hi
101243
hi
101244
hi
101245
hi
101246
hi
101247
hi
101248
hi
101249
hi
101250
hi
101251
hi
101252
hi
101253
hi
101254
hi
101255
hi
101256
hi
101257
hi


In [31]:
np.save(path+'pred_123_test',pred_123_test)

In [32]:
np.load('pred_123_test.npy')

np.sum(pred_123_test == label_123_test)/101702.0

0.9196377652356886

In [34]:
clf1.predict(class_123_test[90000,:].reshape(1,512))

array([1.])

In [35]:
from sklearn.metrics import precision_recall_fscore_support
y_true = label_123_test
y_pred = pred_123_test

print(precision_recall_fscore_support(y_true, y_pred, average='macro'))

(0.8894096282110918, 0.8972619843035835, 0.8931618902399254, None)


In [36]:
print(precision_recall_fscore_support(y_true, y_pred, average='micro'))

(0.9196377652356886, 0.9196377652356886, 0.9196377652356886, None)


In [17]:
a=1
def dsk(num):
    return a + num
print(dsk(1))

2
