In [5]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

import numpy as np  
import openslide  
from openslide import open_slide  

from PIL import Image
from __future__ import print_function
import os


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [8]:


for root, dirs, files in os.walk("/Users/user/Desktop/medical_images/above8/train"):
    for file in files:
        if file.endswith(".svs"):
             print(os.path.join(root, file))
                



/Users/user/Desktop/medical_images/above8/train/135/49185953-7348-4cd0-83ec-844a70c3bc81/TCGA-V1-A9ZR-01A-01-TSA.9D064846-1D67-4499-93F6-1F1813ECD520.svs
/Users/user/Desktop/medical_images/above8/train/132/5b215b2a-42eb-4a2b-89cc-a7813c4129d3/TCGA-V1-A9ZG-01A-01-TSA.689D242F-AC2D-4885-A42E-78583DE7EB03.svs
/Users/user/Desktop/medical_images/above8/train/104/19376e75-1227-4d6f-aecd-2e6ad0cf2d9c/TCGA-EJ-5506-01A-01-BS1.7f8846fa-50c5-4c55-9421-00f418022a18.svs
/Users/user/Desktop/medical_images/above8/train/68/e1a126b1-e8d4-4848-a5ce-ff45220a581c/TCGA-CH-5772-01A-01-BS1.f02d86c3-b8bf-4750-b37b-75ad1b5c92fe.svs
/Users/user/Desktop/medical_images/above8/train/150/7733e25d-bfc3-4ddf-874f-80dcc427616f/TCGA-VP-A879-01A-01-TSA.FA8B87D6-5632-43BF-8D36-A06E14D1EB9E.svs
/Users/user/Desktop/medical_images/above8/train/159/50247561-ddf6-46a3-9c56-922f5f2a3bfb/TCGA-WW-A8ZI-01A-01-TSA.BB4CB36B-72D3-4DBC-A48B-B3D90EFCC873.svs
/Users/user/Desktop/medical_images/above8/train/32/16fc34c3-b215-46e7-a57a-f4

In [11]:
image=openslide.OpenSlide("/Users/user/Desktop/medical_images/above8/train/135/49185953-7348-4cd0-83ec-844a70c3bc81/TCGA-V1-A9ZR-01A-01-TSA.9D064846-1D67-4499-93F6-1F1813ECD520.svs")
#Specify which image/slide it is. For this example I will
#use slide 7. 
#slide = open_slide(files[0])
a,b= image.level_dimensions[0]
im = image.read_region((0,0),0,(a,b))
img=im.convert("RGB")
img=np.asarray(img).astype(np.float32)

MemoryError: Integer overflow in ysize

In [10]:
imgplot = plt.imshow(img.astype(np.float32))

NameError: name 'img' is not defined

NameError: name 'R' is not defined

In [210]:
R=(img[:,:,0])
G=(img[:,:,1])
B=(img[:,:,2])

BR = (100.0*B*256)/((1+R+G)*(1+R+G+B))
#BR = (np.round(1.0*BR/np.max(BR)))*255
BR=BR.astype(np.uint8)


{0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [218]:
#imgplot = plt.imshow(BR)
BR1=Image.fromarray(BR)
BR1.show()


255

1714

(1714, 6100)


0

array([[240, 240, 240, ..., 240, 240, 240],
       [240, 240, 240, ..., 240, 240, 240],
       [240, 240, 240, ..., 240, 240, 240],
       ..., 
       [240, 240, 240, ..., 240, 240, 240],
       [240, 240, 240, ..., 240, 240, 240],
       [240, 240, 240, ..., 240, 240, 240]], dtype=uint8)

array([[481, 481, 481, ..., 481, 481, 481],
       [481, 481, 481, ..., 481, 481, 481],
       [481, 481, 481, ..., 481, 481, 481],
       ..., 
       [481, 481, 481, ..., 481, 481, 481],
       [481, 481, 481, ..., 481, 481, 481],
       [481, 481, 481, ..., 481, 481, 481]])

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])